-- =============================================================
-- MediVault -- Database Schema
-- Target: MySQL 8.0+ / MariaDB 10.5+
-- Note: users.id, doctors.id and institutions.id are GUIDs
--       (CHAR(36)), generated by the application layer.
-- =============================================================

CREATE DATABASE IF NOT EXISTS medivault CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE medivault;

-- -------------------------------------------------------
-- INDEPENDENT REFERENCE TABLES
-- -------------------------------------------------------

CREATE TABLE subscription_plans (
    id               INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name             ENUM('basic', 'medium', 'premium') NOT NULL,
    storage_limit_mb INT           NOT NULL,
    price_annual     DECIMAL(10,2) NOT NULL,
    price_monthly    DECIMAL(10,2) NOT NULL
);

CREATE TABLE institutions (
    id        CHAR(36)     NOT NULL PRIMARY KEY,
    name      VARCHAR(255) NOT NULL,
    type      ENUM('hospital', 'clinic', 'lab', 'pharmacy', 'other') NOT NULL,
    address   VARCHAR(500),
    phone     VARCHAR(50),
    is_active BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE vaccines (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE icpc2_codes (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    chapter     VARCHAR(100)
);

CREATE TABLE medical_specialties (
    id   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

-- config tables: allow adding values without a schema migration
CREATE TABLE genders (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE habit_types (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(30)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE relationship_types (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(30)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE countries (
    id   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code VARCHAR(3)   NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL
);

-- -------------------------------------------------------
-- USERS
-- -------------------------------------------------------

CREATE TABLE users (
    id                    CHAR(36)     NOT NULL PRIMARY KEY,
    utent_number          VARCHAR(50)  NOT NULL UNIQUE,
    fiscal_number         VARCHAR(20)  NOT NULL UNIQUE,
    citizen_number        VARCHAR(20)  NOT NULL UNIQUE,
    email                 VARCHAR(255) NOT NULL UNIQUE,
    password_hash         VARCHAR(255) NOT NULL,
    first_name            VARCHAR(100) NOT NULL,
    last_name             VARCHAR(100) NOT NULL,
    birthday              DATE         NOT NULL,
    biological_gender     ENUM('M', 'F') NOT NULL,
    sex_id                INT          NOT NULL,
    nationality_id        INT          NOT NULL,
    marital_status        VARCHAR(50),
    blood_type            ENUM('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'),
    accepts_transfusion   BOOLEAN      NOT NULL DEFAULT TRUE,
    accepts_resuscitation BOOLEAN      NOT NULL DEFAULT TRUE,
    emergency_access_code BOOLEAN      NOT NULL DEFAULT TRUE,
    is_dependent          BOOLEAN      NOT NULL DEFAULT FALSE,
    profession            VARCHAR(255),
    phone                 VARCHAR(50),
    phone_country_code    VARCHAR(10)  NOT NULL DEFAULT '351',
    is_active             BOOLEAN      NOT NULL DEFAULT TRUE,
    card_active           BOOLEAN      NOT NULL DEFAULT TRUE,
    share_code            VARCHAR(50)  NOT NULL DEFAULT '',
    photo_path            VARCHAR(255),
    language              VARCHAR(5)   NOT NULL DEFAULT 'pt',
    created_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_users_gender      FOREIGN KEY (sex_id)         REFERENCES genders(id),
    CONSTRAINT fk_users_nationality FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- DOCTORS
-- -------------------------------------------------------

CREATE TABLE doctors (
    id               CHAR(36)     NOT NULL PRIMARY KEY,
    ordem_medicos_id VARCHAR(50)  NOT NULL UNIQUE,
    first_name       VARCHAR(100) NOT NULL,
    last_name        VARCHAR(100) NOT NULL,
    email            VARCHAR(255) NOT NULL UNIQUE,
    password_hash    VARCHAR(255) NOT NULL,
    speciality       VARCHAR(255),
    institution_id   CHAR(36)     NOT NULL,
    nationality_id   INT          NOT NULL,
    language         VARCHAR(5)   NOT NULL DEFAULT 'pt',
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_doctors_institution FOREIGN KEY (institution_id) REFERENCES institutions(id),
    CONSTRAINT fk_doctors_nationality FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- USER PROFILE
-- -------------------------------------------------------

CREATE TABLE user_addresses (
    id          INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     CHAR(36)    NOT NULL,
    street      VARCHAR(500),
    city        VARCHAR(100),
    postal_code VARCHAR(20),
    country     VARCHAR(100),
    is_primary  BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE emergency_contacts (
    id      INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id CHAR(36)     NOT NULL,
    type    ENUM('emergency', 'tutor') NOT NULL,
    name    VARCHAR(255) NOT NULL,
    phone   VARCHAR(50),
    address VARCHAR(500),
    CONSTRAINT fk_emergency_contacts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Guardian/dependent relationship between two registered users (KAN-33)
-- e.g. parent/child, legal guardian/incapacitated patient.
-- A guardian has full access to the dependent's data (enforced at application layer).
CREATE TABLE family_guardianships (
    id                 INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    guardian_user_id     CHAR(36) NOT NULL,
    dependent_user_id    CHAR(36) NOT NULL,
    relationship_type_id INT      NOT NULL,
    status                ENUM('pending', 'approved') NOT NULL DEFAULT 'pending',
    is_active            BOOLEAN  NOT NULL DEFAULT TRUE,
    created_at           DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_family_guardianships_guardian     FOREIGN KEY (guardian_user_id)     REFERENCES users(id),
    CONSTRAINT fk_family_guardianships_dependent    FOREIGN KEY (dependent_user_id)    REFERENCES users(id),
    CONSTRAINT fk_family_guardianships_relationship FOREIGN KEY (relationship_type_id) REFERENCES relationship_types(id),
    CONSTRAINT chk_family_guardianships_not_self    CHECK (guardian_user_id <> dependent_user_id)
);

CREATE TABLE female_medical_info (
    id                   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id              CHAR(36)     NOT NULL UNIQUE,
    menarche_age         INT,
    pregnancies          INT          NOT NULL DEFAULT 0,
    births               INT          NOT NULL DEFAULT 0,
    abortions            INT          NOT NULL DEFAULT 0,
    menopause            BOOLEAN      NOT NULL DEFAULT FALSE,
    menopause_age        INT,
    contraceptive_use    BOOLEAN      NOT NULL DEFAULT FALSE,
    intraceptive_method  VARCHAR(255),
    contraceptive_reason VARCHAR(500),
    CONSTRAINT fk_female_medical_info_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- -------------------------------------------------------
-- SUBSCRIPTIONS & LICENSES
-- -------------------------------------------------------

CREATE TABLE user_subscriptions (
    id         INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    CHAR(36) NOT NULL,
    plan_id    INT      NOT NULL,
    card_type  ENUM('SC1', 'SC2') NOT NULL,
    start_date DATE     NOT NULL,
    end_date   DATE,
    is_active  BOOLEAN  NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_user_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
);

CREATE TABLE institution_licenses (
    id             INT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    institution_id CHAR(36) NOT NULL,
    billing_type   ENUM('monthly', 'quarterly', 'semiannual', 'annual') NOT NULL,
    start_date     DATE    NOT NULL,
    end_date       DATE,
    is_active      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_institution_licenses_institution FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

-- -------------------------------------------------------
-- ACCESS CONTROL
-- -------------------------------------------------------

CREATE TABLE access_requests (
    id           INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id      CHAR(36)     NOT NULL,
    doctor_id    CHAR(36)     NOT NULL,
    requested_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at  DATETIME,
    expires_at   DATETIME,
    status       ENUM('pending', 'approved', 'revoked', 'finished') NOT NULL DEFAULT 'pending',
    is_emergency BOOLEAN      NOT NULL DEFAULT FALSE,
    access_code  VARCHAR(100),
    CONSTRAINT fk_access_requests_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_access_requests_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Rule: an access request can only be flagged is_emergency = true if the
-- patient has pre-authorised emergency access (users.emergency_access_code = true)
DELIMITER $$

CREATE TRIGGER trg_access_requests_emergency_consent_insert
BEFORE INSERT ON access_requests
FOR EACH ROW
BEGIN
    IF NEW.is_emergency = TRUE AND NOT EXISTS (
        SELECT 1 FROM users WHERE id = NEW.user_id AND emergency_access_code = TRUE
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'access_requests.is_emergency = true requires users.emergency_access_code = true';
    END IF;
END$$

CREATE TRIGGER trg_access_requests_emergency_consent_update
BEFORE UPDATE ON access_requests
FOR EACH ROW
BEGIN
    IF NEW.is_emergency = TRUE AND NOT EXISTS (
        SELECT 1 FROM users WHERE id = NEW.user_id AND emergency_access_code = TRUE
    ) THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'access_requests.is_emergency = true requires users.emergency_access_code = true';
    END IF;
END$$

DELIMITER ;

-- -------------------------------------------------------
-- FILES
-- -------------------------------------------------------

CREATE TABLE medical_files (
    id          INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     CHAR(36)      NOT NULL,
    file_name   VARCHAR(255)  NOT NULL,
    file_type   VARCHAR(100),
    file_path   VARCHAR(1000) NOT NULL,
    uploaded_by CHAR(36),
    uploaded_at DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_medical_files_user   FOREIGN KEY (user_id)     REFERENCES users(id),
    CONSTRAINT fk_medical_files_doctor FOREIGN KEY (uploaded_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- MEDICAL HISTORY
-- -------------------------------------------------------

CREATE TABLE surgical_history (
    id             INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id        CHAR(36)     NOT NULL,
    surgery_name   VARCHAR(255) NOT NULL,
    surgery_date   DATE,
    location       VARCHAR(255),
    notes          TEXT,
    report_file_id INT,
    added_by       CHAR(36),
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_surgical_history_user   FOREIGN KEY (user_id)        REFERENCES users(id),
    CONSTRAINT fk_surgical_history_file   FOREIGN KEY (report_file_id) REFERENCES medical_files(id),
    CONSTRAINT fk_surgical_history_doctor FOREIGN KEY (added_by)       REFERENCES doctors(id)
);

CREATE TABLE chronic_medications (
    id               INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id          CHAR(36)     NOT NULL,
    active_substance VARCHAR(255) NOT NULL,
    dose             VARCHAR(100),
    posology         VARCHAR(255),
    start_date       DATE,
    end_date         DATE,
    prescribed_by    CHAR(36),
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_chronic_medications_user   FOREIGN KEY (user_id)       REFERENCES users(id),
    CONSTRAINT fk_chronic_medications_doctor FOREIGN KEY (prescribed_by) REFERENCES doctors(id)
);

CREATE TABLE drug_allergies (
    id                INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id           CHAR(36)     NOT NULL,
    active_substance  VARCHAR(255) NOT NULL,
    allergic_reaction VARCHAR(500),
    severity          ENUM('mild', 'moderate', 'severe'),
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_drug_allergies_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE family_history (
    id             INT     NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id        CHAR(36) NOT NULL,
    condition      ENUM('cardiovascular', 'cancer', 'autoimmune', 'genetic', 'ophthalmic', 'psychological', 'consanguinity', 'other') NOT NULL,
    has_condition  BOOLEAN NOT NULL DEFAULT FALSE,
    kinship_degree VARCHAR(100),
    notes          TEXT,
    CONSTRAINT fk_family_history_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_pathologies (
    id           INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id      CHAR(36) NOT NULL,
    icpc2_id     INT      NOT NULL,
    type         ENUM('active', 'passive') NOT NULL,
    diagnosed_at DATE,
    notes        TEXT,
    added_by     CHAR(36),
    CONSTRAINT fk_user_pathologies_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_user_pathologies_icpc2  FOREIGN KEY (icpc2_id) REFERENCES icpc2_codes(id),
    CONSTRAINT fk_user_pathologies_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE user_specialty_followups (
    id           INT  NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id      CHAR(36) NOT NULL,
    specialty_id INT  NOT NULL,
    institution  VARCHAR(255),
    start_date   DATE,
    notes        TEXT,
    CONSTRAINT fk_user_specialty_followups_user      FOREIGN KEY (user_id)      REFERENCES users(id),
    CONSTRAINT fk_user_specialty_followups_specialty FOREIGN KEY (specialty_id) REFERENCES medical_specialties(id)
);

-- -------------------------------------------------------
-- EXAMS (MCDTS)
-- -------------------------------------------------------

CREATE TABLE analytical_exams (
    id         INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    CHAR(36)     NOT NULL,
    exam_date  DATE         NOT NULL,
    laboratory VARCHAR(255),
    file_id    INT,
    notes      TEXT,
    added_by   CHAR(36),
    is_active  BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_analytical_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_analytical_exams_file   FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    CONSTRAINT fk_analytical_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE analytical_exam_parameters (
    id             INT           NOT NULL AUTO_INCREMENT PRIMARY KEY,
    exam_id        INT           NOT NULL,
    parameter_name VARCHAR(255)  NOT NULL,
    value          DECIMAL(18,6),
    unit           VARCHAR(50),
    reference_min  DECIMAL(18,6),
    reference_max  DECIMAL(18,6),
    is_abnormal    BOOLEAN       NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_analytical_exam_parameters_exam FOREIGN KEY (exam_id) REFERENCES analytical_exams(id)
);

CREATE TABLE imaging_exams (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     CHAR(36)     NOT NULL,
    exam_type   VARCHAR(100) NOT NULL,
    body_area   VARCHAR(100),
    exam_date   DATE         NOT NULL,
    institution VARCHAR(255),
    file_id     INT,
    report_text TEXT,
    added_by    CHAR(36),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_imaging_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_imaging_exams_file   FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    CONSTRAINT fk_imaging_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE optometry_exams (
    id             INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id        CHAR(36)     NOT NULL,
    exam_date      DATE         NOT NULL,
    right_sphere   DECIMAL(5,2),
    right_cylinder DECIMAL(5,2),
    right_axis     INT,
    left_sphere    DECIMAL(5,2),
    left_cylinder  DECIMAL(5,2),
    left_axis      INT,
    disease_report TEXT,
    added_by       CHAR(36),
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_optometry_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_optometry_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VACCINATIONS
-- -------------------------------------------------------

CREATE TABLE user_vaccinations (
    id              INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id         CHAR(36)     NOT NULL,
    vaccine_id      INT          NOT NULL,
    dose_number     VARCHAR(20),
    administered_at DATE,
    next_due_date   DATE,
    batch_number    VARCHAR(100),
    institution     VARCHAR(255),
    notes           TEXT,
    added_by        CHAR(36),
    CONSTRAINT fk_user_vaccinations_user    FOREIGN KEY (user_id)    REFERENCES users(id),
    CONSTRAINT fk_user_vaccinations_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    CONSTRAINT fk_user_vaccinations_doctor  FOREIGN KEY (added_by)   REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- HEALTH HABITS (consolidated)
-- details (JSON): type-specific fields
--   alcohol  -> { consumes, alcohol_type, in_detox, audit_c_score, audit_score }
--   tobacco  -> { consumes, cigarettes_per_day, years_consumption, pack_years, fagerstrom_score, richmond_score }
--   drugs    -> { drug_name, quantity }
--   gambling -> { game_name }
--   physical_activity -> { activity }
-- -------------------------------------------------------

CREATE TABLE health_habits (
    id         INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    CHAR(36) NOT NULL,
    type_id    INT      NOT NULL,
    name       VARCHAR(255),
    consumes   BOOLEAN,
    frequency  VARCHAR(100),
    quantity   VARCHAR(100),
    start_date DATE,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    details    JSON,
    CONSTRAINT fk_health_habits_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_health_habits_type FOREIGN KEY (type_id) REFERENCES habit_types(id)
);

-- -------------------------------------------------------
-- DOCTOR NOTES & FLAGS
-- note_text stored encrypted (application-layer encryption)
-- -------------------------------------------------------

CREATE TABLE doctor_notes (
    id         INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    CHAR(36) NOT NULL,
    doctor_id  CHAR(36) NOT NULL,
    section    ENUM('identification', 'medical_info', 'mcdts', 'habits', 'history', 'other') NOT NULL,
    note_text  LONGBLOB,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_doctor_notes_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_doctor_notes_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE pending_review_flags (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     CHAR(36)     NOT NULL,
    section     VARCHAR(100) NOT NULL,
    created_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_at DATETIME,
    reviewed_by CHAR(36),
    CONSTRAINT fk_pending_review_flags_user   FOREIGN KEY (user_id)     REFERENCES users(id),
    CONSTRAINT fk_pending_review_flags_doctor FOREIGN KEY (reviewed_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VERSIONING
-- -------------------------------------------------------

CREATE TABLE schema_versions (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    version     VARCHAR(20)  NOT NULL,
    description VARCHAR(255),
    script      VARCHAR(255),
    applied_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    applied_by  VARCHAR(100),
    checksum    VARCHAR(64),
    success     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE app_versions (
    id           INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    version      VARCHAR(20)  NOT NULL,
    release_date DATE,
    description  VARCHAR(255),
    deployed_at  DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deployed_by  VARCHAR(100),
    environment  ENUM('dev', 'staging', 'prod') NOT NULL,
    is_current   BOOLEAN      NOT NULL DEFAULT FALSE
);

-- -------------------------------------------------------
-- SCHEDULING & AGENDA
-- -------------------------------------------------------

CREATE TABLE schedule_event_types (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE appointment_types (
    id          INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL UNIQUE,
    description VARCHAR(255)
);

CREATE TABLE institution_contacts (
    id             INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    institution_id CHAR(36)     NOT NULL,
    service_name   VARCHAR(255) NOT NULL,
    extension      VARCHAR(50)  NOT NULL,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_institution_contacts_institution FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

CREATE TABLE doctor_schedule_events (
    id            INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    doctor_id     CHAR(36)     NOT NULL,
    event_type_id INT          NOT NULL,
    title         VARCHAR(255) NOT NULL,
    location      VARCHAR(255),
    start_date    DATE         NOT NULL,
    end_date      DATE         NOT NULL,
    notes         TEXT,
    created_at    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_doctor_schedule_events_dates CHECK (end_date >= start_date),
    CONSTRAINT fk_doctor_schedule_events_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT fk_doctor_schedule_events_type   FOREIGN KEY (event_type_id) REFERENCES schedule_event_types(id)
);

DELIMITER $$
-- Prevent overlapping schedule events (congress/training/vacation) for the same doctor
CREATE TRIGGER trg_doctor_schedule_events_no_overlap_insert
BEFORE INSERT ON doctor_schedule_events
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 FROM doctor_schedule_events
        WHERE doctor_id = NEW.doctor_id
          AND NEW.start_date <= end_date
          AND NEW.end_date >= start_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'doctor_schedule_events: overlapping date range for this doctor';
    END IF;
END$$

CREATE TRIGGER trg_doctor_schedule_events_no_overlap_update
BEFORE UPDATE ON doctor_schedule_events
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 FROM doctor_schedule_events
        WHERE doctor_id = NEW.doctor_id
          AND id <> NEW.id
          AND NEW.start_date <= end_date
          AND NEW.end_date >= start_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'doctor_schedule_events: overlapping date range for this doctor';
    END IF;
END$$
DELIMITER ;

CREATE TABLE patient_appointments (
    id                   INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id              CHAR(36)     NOT NULL,
    doctor_id            CHAR(36)     NOT NULL,
    appointment_type_id  INT          NOT NULL,
    modality             ENUM('presencial', 'teleconsulta') NOT NULL,
    scheduled_at         DATETIME     NOT NULL,
    status               ENUM('pendente', 'confirmada', 'em_curso', 'concluida', 'cancelada') NOT NULL DEFAULT 'confirmada',
    created_by_role      ENUM('doctor', 'staff') NOT NULL,
    created_by_doctor_id CHAR(36),
    notes                TEXT,
    created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_patient_appointments_created_by CHECK (
        (created_by_role = 'doctor' AND created_by_doctor_id IS NOT NULL) OR
        (created_by_role = 'staff'  AND created_by_doctor_id IS NULL)
    ),
    CONSTRAINT fk_patient_appointments_user             FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_patient_appointments_doctor           FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT fk_patient_appointments_type             FOREIGN KEY (appointment_type_id) REFERENCES appointment_types(id),
    CONSTRAINT fk_patient_appointments_created_by_doctor FOREIGN KEY (created_by_doctor_id) REFERENCES doctors(id)
);

DELIMITER $$
-- Prevent double-booking: same doctor cannot have two active appointments at the same scheduled_at
CREATE TRIGGER trg_patient_appointments_no_overlap_insert
BEFORE INSERT ON patient_appointments
FOR EACH ROW
BEGIN
    IF NEW.status <> 'cancelada' AND EXISTS (
        SELECT 1 FROM patient_appointments
        WHERE doctor_id = NEW.doctor_id
          AND scheduled_at = NEW.scheduled_at
          AND status <> 'cancelada'
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'patient_appointments: doctor already has an appointment at this time';
    END IF;
END$$

CREATE TRIGGER trg_patient_appointments_no_overlap_update
BEFORE UPDATE ON patient_appointments
FOR EACH ROW
BEGIN
    IF NEW.status <> 'cancelada' AND EXISTS (
        SELECT 1 FROM patient_appointments
        WHERE doctor_id = NEW.doctor_id
          AND scheduled_at = NEW.scheduled_at
          AND status <> 'cancelada'
          AND id <> NEW.id
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'patient_appointments: doctor already has an appointment at this time';
    END IF;
END$$
DELIMITER ;

DELIMITER $$
-- Prevent a patient appointment on a date the doctor has a scheduled event (congress/training/vacation)
CREATE TRIGGER trg_patient_appointments_no_schedule_conflict_insert
BEFORE INSERT ON patient_appointments
FOR EACH ROW
BEGIN
    IF NEW.status <> 'cancelada' AND EXISTS (
        SELECT 1 FROM doctor_schedule_events
        WHERE doctor_id = NEW.doctor_id
          AND DATE(NEW.scheduled_at) BETWEEN start_date AND end_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'patient_appointments: doctor has a schedule event covering this date';
    END IF;
END$$

CREATE TRIGGER trg_patient_appointments_no_schedule_conflict_update
BEFORE UPDATE ON patient_appointments
FOR EACH ROW
BEGIN
    IF NEW.status <> 'cancelada' AND EXISTS (
        SELECT 1 FROM doctor_schedule_events
        WHERE doctor_id = NEW.doctor_id
          AND DATE(NEW.scheduled_at) BETWEEN start_date AND end_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'patient_appointments: doctor has a schedule event covering this date';
    END IF;
END$$

-- Prevent scheduling a doctor event (congress/training/vacation) over a date with an active patient appointment
CREATE TRIGGER trg_doctor_schedule_events_no_appointment_conflict_insert
BEFORE INSERT ON doctor_schedule_events
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 FROM patient_appointments
        WHERE doctor_id = NEW.doctor_id
          AND status <> 'cancelada'
          AND DATE(scheduled_at) BETWEEN NEW.start_date AND NEW.end_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'doctor_schedule_events: doctor already has an appointment within this date range';
    END IF;
END$$

CREATE TRIGGER trg_doctor_schedule_events_no_appointment_conflict_update
BEFORE UPDATE ON doctor_schedule_events
FOR EACH ROW
BEGIN
    IF EXISTS (
        SELECT 1 FROM patient_appointments
        WHERE doctor_id = NEW.doctor_id
          AND status <> 'cancelada'
          AND DATE(scheduled_at) BETWEEN NEW.start_date AND NEW.end_date
    ) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'doctor_schedule_events: doctor already has an appointment within this date range';
    END IF;
END$$
DELIMITER ;

-- -------------------------------------------------------
-- CLINICAL CONSULTATION RECORDS
-- -------------------------------------------------------

CREATE TABLE vital_signs (
    id                       INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id                  CHAR(36)     NOT NULL,
    doctor_id                CHAR(36)     NOT NULL,
    recorded_at              DATETIME     NOT NULL,
    blood_pressure_systolic  INT,
    blood_pressure_diastolic INT,
    heart_rate               INT,
    respiratory_rate         INT,
    temperature              DECIMAL(4,1),
    spo2                     INT,
    weight                   DECIMAL(5,2),
    height                   DECIMAL(5,2),
    notes                    TEXT,
    created_at               DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_vital_signs_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_vital_signs_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE clinical_assessments (
    id         INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    CHAR(36)     NOT NULL,
    doctor_id  CHAR(36)     NOT NULL,
    hypothesis TEXT         NOT NULL,
    plan       TEXT         NOT NULL,
    created_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_clinical_assessments_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_clinical_assessments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Anamnesis is historical: every save creates a new row. Editing an existing row
-- is only allowed application-side for the SAME doctor_id, within 24h of created_at.
CREATE TABLE anamneses (
    id               INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id          CHAR(36)     NOT NULL,
    doctor_id        CHAR(36)     NOT NULL,
    chief_complaint  TEXT,
    illness_history  TEXT,
    personal_history TEXT,
    created_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at       DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_anamneses_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_anamneses_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Team chat: doctors discussing a patient's case amongst themselves.
CREATE TABLE patient_chat_messages (
    id                INT          NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id           CHAR(36)     NOT NULL,
    author_doctor_id  CHAR(36)     NOT NULL,
    message           TEXT         NOT NULL,
    created_at        DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_patient_chat_messages_user   FOREIGN KEY (user_id)          REFERENCES users(id),
    CONSTRAINT fk_patient_chat_messages_author FOREIGN KEY (author_doctor_id) REFERENCES doctors(id)
);

-- A consultation session: a doctor's visit to a patient, saved as a draft while in
-- progress and closed by finishing it (status -> 'finished', finished_at set).
CREATE TABLE consultations (
    id          INT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id     CHAR(36) NOT NULL,
    doctor_id   CHAR(36) NOT NULL,
    status      ENUM('draft', 'finished') NOT NULL DEFAULT 'draft',
    started_at  DATETIME NOT NULL,
    finished_at DATETIME,
    created_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_consultations_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_consultations_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);
