-- =============================================================
-- MediVault -- Database Schema
-- Target: SQLite (3.x)
-- Note: users.id, doctors.id and institutions.id are GUIDs
--       (TEXT, 36-char string), generated by the application layer.
-- =============================================================

PRAGMA foreign_keys = ON;

-- -------------------------------------------------------
-- INDEPENDENT REFERENCE TABLES
-- -------------------------------------------------------

CREATE TABLE subscription_plans (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    name             TEXT    NOT NULL CHECK (name IN ('basic', 'medium', 'premium')),
    storage_limit_mb INTEGER NOT NULL,
    price_annual     REAL    NOT NULL,
    price_monthly    REAL    NOT NULL
);

CREATE TABLE institutions (
    id        TEXT    PRIMARY KEY,
    name      TEXT    NOT NULL,
    type      TEXT    NOT NULL CHECK (type IN ('hospital', 'clinic', 'lab', 'pharmacy', 'other')),
    address   TEXT,
    phone     TEXT,
    is_active INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE vaccines (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT NOT NULL,
    description TEXT
);

CREATE TABLE icpc2_codes (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    chapter     TEXT
);

CREATE TABLE medical_specialties (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL
);

-- config tables: allow adding values without a schema migration
CREATE TABLE genders (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT    NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE habit_types (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT    NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE relationship_types (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    code        TEXT    NOT NULL UNIQUE,
    description TEXT
);

CREATE TABLE countries (
    id   INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT    NOT NULL UNIQUE,
    name TEXT    NOT NULL
);

-- -------------------------------------------------------
-- USERS
-- -------------------------------------------------------

CREATE TABLE users (
    id                    TEXT    PRIMARY KEY,
    utent_number          TEXT    NOT NULL UNIQUE,
    fiscal_number         TEXT    NOT NULL UNIQUE,
    citizen_number        TEXT    NOT NULL UNIQUE,
    email                 TEXT    NOT NULL UNIQUE,
    password_hash         TEXT    NOT NULL,
    first_name            TEXT    NOT NULL,
    last_name             TEXT    NOT NULL,
    birthday              TEXT    NOT NULL,
    biological_gender     TEXT    NOT NULL CHECK (biological_gender IN ('M', 'F')),
    sex_id                INTEGER NOT NULL,
    nationality_id        INTEGER NOT NULL,
    marital_status        TEXT,
    blood_type            TEXT    CHECK (blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    accepts_transfusion   INTEGER NOT NULL DEFAULT 1,
    accepts_resuscitation INTEGER NOT NULL DEFAULT 1,
    emergency_access_code INTEGER NOT NULL DEFAULT 1,
    is_dependent          INTEGER NOT NULL DEFAULT 0,
    profession            TEXT,
    phone                 TEXT,
    is_active             INTEGER NOT NULL DEFAULT 1,
    card_active           INTEGER NOT NULL DEFAULT 1,
    created_at            TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at            TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (sex_id) REFERENCES genders(id),
    FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- DOCTORS
-- -------------------------------------------------------

CREATE TABLE doctors (
    id               TEXT    PRIMARY KEY,
    ordem_medicos_id TEXT    NOT NULL UNIQUE,
    first_name       TEXT    NOT NULL,
    last_name        TEXT    NOT NULL,
    email            TEXT    NOT NULL UNIQUE,
    password_hash    TEXT    NOT NULL,
    speciality       TEXT,
    institution_id   TEXT    NOT NULL,
    nationality_id   INTEGER NOT NULL,
    is_active        INTEGER NOT NULL DEFAULT 1,
    created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (institution_id) REFERENCES institutions(id),
    FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- USER PROFILE
-- -------------------------------------------------------

CREATE TABLE user_addresses (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     TEXT    NOT NULL,
    street      TEXT,
    city        TEXT,
    postal_code TEXT,
    country     TEXT,
    is_primary  INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE emergency_contacts (
    id      INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT    NOT NULL,
    type    TEXT    NOT NULL CHECK (type IN ('emergency', 'tutor')),
    name    TEXT    NOT NULL,
    phone   TEXT,
    address TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Guardian/dependent relationship between two registered users (KAN-33)
-- e.g. parent/child, legal guardian/incapacitated patient.
-- A guardian has full access to the dependent's data (enforced at application layer).
CREATE TABLE family_guardianships (
    id                 INTEGER PRIMARY KEY AUTOINCREMENT,
    guardian_user_id     TEXT    NOT NULL,
    dependent_user_id    TEXT    NOT NULL,
    relationship_type_id INTEGER NOT NULL,
    is_active            INTEGER NOT NULL DEFAULT 1,
    created_at           TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (guardian_user_id)     REFERENCES users(id),
    FOREIGN KEY (dependent_user_id)    REFERENCES users(id),
    FOREIGN KEY (relationship_type_id) REFERENCES relationship_types(id),
    CHECK (guardian_user_id <> dependent_user_id)
);

CREATE TABLE female_medical_info (
    id                   INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id              TEXT    NOT NULL UNIQUE,
    menarche_age         INTEGER,
    pregnancies          INTEGER NOT NULL DEFAULT 0,
    births               INTEGER NOT NULL DEFAULT 0,
    abortions            INTEGER NOT NULL DEFAULT 0,
    menopause            INTEGER NOT NULL DEFAULT 0,
    menopause_age        INTEGER,
    contraceptive_use    INTEGER NOT NULL DEFAULT 0,
    intraceptive_method  TEXT,
    contraceptive_reason TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- -------------------------------------------------------
-- SUBSCRIPTIONS & LICENSES
-- -------------------------------------------------------

CREATE TABLE user_subscriptions (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT    NOT NULL,
    plan_id    INTEGER NOT NULL,
    card_type  TEXT    NOT NULL CHECK (card_type IN ('SC1', 'SC2')),
    start_date TEXT    NOT NULL,
    end_date   TEXT,
    is_active  INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
);

CREATE TABLE institution_licenses (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    institution_id TEXT    NOT NULL,
    billing_type   TEXT    NOT NULL CHECK (billing_type IN ('monthly', 'quarterly', 'semiannual', 'annual')),
    start_date     TEXT    NOT NULL,
    end_date       TEXT,
    is_active      INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

-- -------------------------------------------------------
-- ACCESS CONTROL
-- -------------------------------------------------------

CREATE TABLE access_requests (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      TEXT    NOT NULL,
    doctor_id    TEXT    NOT NULL,
    requested_at TEXT    NOT NULL DEFAULT (datetime('now')),
    approved_at  TEXT,
    expires_at   TEXT,
    status       TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'revoked')),
    is_emergency INTEGER NOT NULL DEFAULT 0,
    access_code  TEXT,
    FOREIGN KEY (user_id)   REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Rule: an access request can only be flagged is_emergency = 1 if the
-- patient has pre-authorised emergency access (users.emergency_access_code = 1)
CREATE TRIGGER trg_access_requests_emergency_consent_insert
BEFORE INSERT ON access_requests
FOR EACH ROW
WHEN NEW.is_emergency = 1 AND NOT EXISTS (
    SELECT 1 FROM users WHERE id = NEW.user_id AND emergency_access_code = 1
)
BEGIN
    SELECT RAISE(ABORT, 'access_requests.is_emergency = 1 requires users.emergency_access_code = 1');
END;

CREATE TRIGGER trg_access_requests_emergency_consent_update
BEFORE UPDATE ON access_requests
FOR EACH ROW
WHEN NEW.is_emergency = 1 AND NOT EXISTS (
    SELECT 1 FROM users WHERE id = NEW.user_id AND emergency_access_code = 1
)
BEGIN
    SELECT RAISE(ABORT, 'access_requests.is_emergency = 1 requires users.emergency_access_code = 1');
END;

-- -------------------------------------------------------
-- FILES
-- -------------------------------------------------------

CREATE TABLE medical_files (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     TEXT    NOT NULL,
    file_name   TEXT    NOT NULL,
    file_type   TEXT,
    file_path   TEXT    NOT NULL,
    uploaded_by TEXT,
    uploaded_at TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)     REFERENCES users(id),
    FOREIGN KEY (uploaded_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- MEDICAL HISTORY
-- -------------------------------------------------------

CREATE TABLE surgical_history (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id        TEXT    NOT NULL,
    surgery_name   TEXT    NOT NULL,
    surgery_date   TEXT,
    location       TEXT,
    notes          TEXT,
    report_file_id INTEGER,
    added_by       TEXT,
    is_active      INTEGER NOT NULL DEFAULT 1,
    created_at     TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)        REFERENCES users(id),
    FOREIGN KEY (report_file_id) REFERENCES medical_files(id),
    FOREIGN KEY (added_by)       REFERENCES doctors(id)
);

CREATE TABLE chronic_medications (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id          TEXT    NOT NULL,
    active_substance TEXT    NOT NULL,
    dose             TEXT,
    posology         TEXT,
    start_date       TEXT,
    end_date         TEXT,
    prescribed_by    TEXT,
    is_active        INTEGER NOT NULL DEFAULT 1,
    created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)      REFERENCES users(id),
    FOREIGN KEY (prescribed_by) REFERENCES doctors(id)
);

CREATE TABLE drug_allergies (
    id                INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id           TEXT    NOT NULL,
    active_substance  TEXT    NOT NULL,
    allergic_reaction TEXT,
    severity          TEXT    CHECK (severity IN ('mild', 'moderate', 'severe')),
    created_at        TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE family_history (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id        TEXT    NOT NULL,
    condition      TEXT    NOT NULL CHECK (condition IN ('cardiovascular', 'cancer', 'autoimmune', 'genetic', 'ophthalmic', 'psychological', 'consanguinity', 'other')),
    has_condition  INTEGER NOT NULL DEFAULT 0,
    kinship_degree TEXT,
    notes          TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_pathologies (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      TEXT    NOT NULL,
    icpc2_id     INTEGER NOT NULL,
    type         TEXT    NOT NULL CHECK (type IN ('active', 'passive')),
    diagnosed_at TEXT,
    notes        TEXT,
    added_by     TEXT,
    FOREIGN KEY (user_id)  REFERENCES users(id),
    FOREIGN KEY (icpc2_id) REFERENCES icpc2_codes(id),
    FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE user_specialty_followups (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id      TEXT    NOT NULL,
    specialty_id INTEGER NOT NULL,
    institution  TEXT,
    start_date   TEXT,
    notes        TEXT,
    FOREIGN KEY (user_id)      REFERENCES users(id),
    FOREIGN KEY (specialty_id) REFERENCES medical_specialties(id)
);

-- -------------------------------------------------------
-- EXAMS (MCDTS)
-- -------------------------------------------------------

CREATE TABLE analytical_exams (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT    NOT NULL,
    exam_date  TEXT    NOT NULL,
    laboratory TEXT,
    file_id    INTEGER,
    notes      TEXT,
    added_by   TEXT,
    is_active  INTEGER NOT NULL DEFAULT 1,
    created_at TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)  REFERENCES users(id),
    FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE analytical_exam_parameters (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    exam_id        INTEGER NOT NULL,
    parameter_name TEXT    NOT NULL,
    value          REAL,
    unit           TEXT,
    reference_min  REAL,
    reference_max  REAL,
    is_abnormal    INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (exam_id) REFERENCES analytical_exams(id)
);

CREATE TABLE imaging_exams (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     TEXT    NOT NULL,
    exam_type   TEXT    NOT NULL,
    body_area   TEXT,
    exam_date   TEXT    NOT NULL,
    institution TEXT,
    file_id     INTEGER,
    report_text TEXT,
    added_by    TEXT,
    is_active   INTEGER NOT NULL DEFAULT 1,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)  REFERENCES users(id),
    FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE optometry_exams (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id        TEXT    NOT NULL,
    exam_date      TEXT    NOT NULL,
    right_sphere   REAL,
    right_cylinder REAL,
    right_axis     INTEGER,
    left_sphere    REAL,
    left_cylinder  REAL,
    left_axis      INTEGER,
    disease_report TEXT,
    added_by       TEXT,
    is_active      INTEGER NOT NULL DEFAULT 1,
    created_at     TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)  REFERENCES users(id),
    FOREIGN KEY (added_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VACCINATIONS
-- -------------------------------------------------------

CREATE TABLE user_vaccinations (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id         TEXT    NOT NULL,
    vaccine_id      INTEGER NOT NULL,
    dose_number     TEXT,
    administered_at TEXT,
    next_due_date   TEXT,
    batch_number    TEXT,
    institution     TEXT,
    notes           TEXT,
    added_by        TEXT,
    FOREIGN KEY (user_id)    REFERENCES users(id),
    FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    FOREIGN KEY (added_by)   REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- HEALTH HABITS (consolidated)
-- details (JSON text): type-specific fields
--   alcohol  -> { consumes, alcohol_type, in_detox, audit_c_score, audit_score }
--   tobacco  -> { consumes, cigarettes_per_day, years_consumption, pack_years, fagerstrom_score, richmond_score }
--   drugs    -> { drug_name, quantity }
--   gambling -> { game_name }
--   physical_activity -> { activity }
-- -------------------------------------------------------

CREATE TABLE health_habits (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT    NOT NULL,
    type_id    INTEGER NOT NULL,
    name       TEXT,
    consumes   INTEGER,
    frequency  TEXT,
    quantity   TEXT,
    start_date TEXT,
    updated_at TEXT    NOT NULL DEFAULT (datetime('now')),
    details    TEXT,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (type_id) REFERENCES habit_types(id)
);

-- -------------------------------------------------------
-- DOCTOR NOTES & FLAGS
-- note_text stored as BLOB (application-layer encryption)
-- -------------------------------------------------------

CREATE TABLE doctor_notes (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT    NOT NULL,
    doctor_id  TEXT    NOT NULL,
    section    TEXT    NOT NULL CHECK (section IN ('identification', 'medical_info', 'mcdts', 'habits', 'history', 'other')),
    note_text  BLOB,
    created_at TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id)   REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE pending_review_flags (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id     TEXT    NOT NULL,
    section     TEXT    NOT NULL,
    created_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    reviewed_at TEXT,
    reviewed_by TEXT,
    FOREIGN KEY (user_id)     REFERENCES users(id),
    FOREIGN KEY (reviewed_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VERSIONING
-- -------------------------------------------------------

CREATE TABLE schema_versions (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    version     TEXT    NOT NULL,
    description TEXT,
    script      TEXT,
    applied_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    applied_by  TEXT,
    checksum    TEXT,
    success     INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE app_versions (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    version      TEXT    NOT NULL,
    release_date TEXT,
    description  TEXT,
    deployed_at  TEXT    NOT NULL DEFAULT (datetime('now')),
    deployed_by  TEXT,
    environment  TEXT    NOT NULL CHECK (environment IN ('dev', 'staging', 'prod')),
    is_current   INTEGER NOT NULL DEFAULT 0
);

-- CLINICAL CONSULTATION RECORDS
-- -------------------------------------------------------

CREATE TABLE vital_signs (
    id                       INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id                  TEXT    NOT NULL,
    doctor_id                TEXT    NOT NULL,
    recorded_at              TEXT    NOT NULL,
    blood_pressure_systolic  INTEGER,
    blood_pressure_diastolic INTEGER,
    heart_rate               INTEGER,
    respiratory_rate         INTEGER,
    temperature              REAL,
    spo2                     INTEGER,
    weight                   REAL,
    height                   REAL,
    notes                    TEXT,
    created_at               TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE clinical_assessments (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id    TEXT    NOT NULL,
    doctor_id  TEXT    NOT NULL,
    hypothesis TEXT    NOT NULL,
    plan       TEXT    NOT NULL,
    created_at TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

-- Anamnesis is historical: every save creates a new row. Editing an existing row
-- is only allowed application-side for the SAME doctor_id, within 24h of created_at.
CREATE TABLE anamneses (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id          TEXT    NOT NULL,
    doctor_id        TEXT    NOT NULL,
    chief_complaint  TEXT,
    illness_history  TEXT,
    personal_history TEXT,
    created_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    updated_at       TEXT    NOT NULL DEFAULT (datetime('now')),
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);
