-- =============================================================
-- MediVault -- Database Schema
-- Target: SQL Server (2016+)
-- Note: users.id, doctors.id and institutions.id are GUIDs
--       (UNIQUEIDENTIFIER), generated by the application layer.
-- =============================================================

-- -------------------------------------------------------
-- INDEPENDENT REFERENCE TABLES
-- -------------------------------------------------------

CREATE TABLE subscription_plans (
    id            INT            IDENTITY(1,1) PRIMARY KEY,
    name          NVARCHAR(20)   NOT NULL CHECK (name IN ('basic', 'medium', 'premium')),
    storage_limit_mb INT         NOT NULL,
    price_annual  DECIMAL(10,2)  NOT NULL,
    price_monthly DECIMAL(10,2)  NOT NULL
);

CREATE TABLE institutions (
    id        UNIQUEIDENTIFIER PRIMARY KEY,
    name      NVARCHAR(255) NOT NULL,
    type      NVARCHAR(20)  NOT NULL CHECK (type IN ('hospital', 'clinic', 'lab', 'pharmacy', 'other')),
    address   NVARCHAR(500),
    phone     NVARCHAR(50),
    is_active BIT           NOT NULL DEFAULT 1
);

CREATE TABLE vaccines (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    name        NVARCHAR(255) NOT NULL,
    description NVARCHAR(1000)
);

CREATE TABLE icpc2_codes (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    code        NVARCHAR(10)  NOT NULL UNIQUE,
    description NVARCHAR(500) NOT NULL,
    chapter     NVARCHAR(100)
);

CREATE TABLE medical_specialties (
    id   INT           IDENTITY(1,1) PRIMARY KEY,
    name NVARCHAR(255) NOT NULL
);

-- config tables: allow adding values without a schema migration
CREATE TABLE genders (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    code        NVARCHAR(20)  NOT NULL UNIQUE,
    description NVARCHAR(255)
);

CREATE TABLE habit_types (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    code        NVARCHAR(30)  NOT NULL UNIQUE,
    description NVARCHAR(255)
);

CREATE TABLE relationship_types (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    code        NVARCHAR(30)  NOT NULL UNIQUE,
    description NVARCHAR(255)
);

CREATE TABLE countries (
    id   INT          IDENTITY(1,1) PRIMARY KEY,
    code NVARCHAR(3)  NOT NULL UNIQUE,
    name NVARCHAR(100) NOT NULL
);

-- -------------------------------------------------------
-- USERS
-- -------------------------------------------------------

CREATE TABLE users (
    id                    UNIQUEIDENTIFIER PRIMARY KEY,
    utent_number          NVARCHAR(50)  NOT NULL UNIQUE,
    fiscal_number         NVARCHAR(20)  NOT NULL UNIQUE,
    citizen_number        NVARCHAR(20)  NOT NULL UNIQUE,
    email                 NVARCHAR(255) NOT NULL UNIQUE,
    password_hash         NVARCHAR(255) NOT NULL,
    first_name            NVARCHAR(100) NOT NULL,
    last_name             NVARCHAR(100) NOT NULL,
    birthday              DATE          NOT NULL,
    biological_gender     NVARCHAR(1)   NOT NULL CHECK (biological_gender IN ('M', 'F')),
    sex_id                INT           NOT NULL,
    nationality_id        INT           NOT NULL,
    marital_status        NVARCHAR(50),
    blood_type            NVARCHAR(5)   CHECK (blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')),
    accepts_transfusion   BIT           NOT NULL DEFAULT 1,
    accepts_resuscitation BIT           NOT NULL DEFAULT 1,
    emergency_access_code BIT           NOT NULL DEFAULT 1,
    is_dependent          BIT           NOT NULL DEFAULT 0,
    profession            NVARCHAR(255),
    phone                 NVARCHAR(50),
    is_active             BIT           NOT NULL DEFAULT 1,
    card_active           BIT           NOT NULL DEFAULT 1,
    photo_path            NVARCHAR(255),
    created_at            DATETIME2     NOT NULL DEFAULT GETDATE(),
    updated_at            DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_users_gender      FOREIGN KEY (sex_id)         REFERENCES genders(id),
    CONSTRAINT fk_users_nationality FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- DOCTORS
-- -------------------------------------------------------

CREATE TABLE doctors (
    id               UNIQUEIDENTIFIER PRIMARY KEY,
    ordem_medicos_id NVARCHAR(50)  NOT NULL UNIQUE,
    first_name       NVARCHAR(100) NOT NULL,
    last_name        NVARCHAR(100) NOT NULL,
    email            NVARCHAR(255) NOT NULL UNIQUE,
    password_hash    NVARCHAR(255) NOT NULL,
    speciality       NVARCHAR(255),
    institution_id   UNIQUEIDENTIFIER NOT NULL,
    nationality_id   INT           NOT NULL,
    is_active        BIT           NOT NULL DEFAULT 1,
    created_at       DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_doctors_institution  FOREIGN KEY (institution_id) REFERENCES institutions(id),
    CONSTRAINT fk_doctors_nationality  FOREIGN KEY (nationality_id) REFERENCES countries(id)
);

-- -------------------------------------------------------
-- USER PROFILE
-- -------------------------------------------------------

CREATE TABLE user_addresses (
    id         INT           IDENTITY(1,1) PRIMARY KEY,
    user_id    UNIQUEIDENTIFIER NOT NULL,
    street     NVARCHAR(500),
    city       NVARCHAR(100),
    postal_code NVARCHAR(20),
    country    NVARCHAR(100),
    is_primary BIT           NOT NULL DEFAULT 0,
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE emergency_contacts (
    id      INT           IDENTITY(1,1) PRIMARY KEY,
    user_id UNIQUEIDENTIFIER NOT NULL,
    type    NVARCHAR(20)  NOT NULL CHECK (type IN ('emergency', 'tutor')),
    name    NVARCHAR(255) NOT NULL,
    phone   NVARCHAR(50),
    address NVARCHAR(500),
    CONSTRAINT fk_emergency_contacts_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- Guardian/dependent relationship between two registered users (KAN-33)
-- e.g. parent/child, legal guardian/incapacitated patient.
-- A guardian has full access to the dependent's data (enforced at application layer).
CREATE TABLE family_guardianships (
    id                INT           IDENTITY(1,1) PRIMARY KEY,
    guardian_user_id     UNIQUEIDENTIFIER NOT NULL,
    dependent_user_id    UNIQUEIDENTIFIER NOT NULL,
    relationship_type_id INT           NOT NULL,
    is_active            BIT           NOT NULL DEFAULT 1,
    created_at           DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_family_guardianships_guardian     FOREIGN KEY (guardian_user_id)     REFERENCES users(id),
    CONSTRAINT fk_family_guardianships_dependent    FOREIGN KEY (dependent_user_id)    REFERENCES users(id),
    CONSTRAINT fk_family_guardianships_relationship FOREIGN KEY (relationship_type_id) REFERENCES relationship_types(id),
    CONSTRAINT chk_family_guardianships_not_self    CHECK (guardian_user_id <> dependent_user_id)
);

CREATE TABLE female_medical_info (
    id                   INT           IDENTITY(1,1) PRIMARY KEY,
    user_id              UNIQUEIDENTIFIER NOT NULL UNIQUE,
    menarche_age         INT,
    pregnancies          INT           NOT NULL DEFAULT 0,
    births               INT           NOT NULL DEFAULT 0,
    abortions            INT           NOT NULL DEFAULT 0,
    menopause            BIT           NOT NULL DEFAULT 0,
    menopause_age        INT,
    contraceptive_use    BIT           NOT NULL DEFAULT 0,
    intraceptive_method  NVARCHAR(255),
    contraceptive_reason NVARCHAR(500),
    CONSTRAINT fk_female_medical_info_user FOREIGN KEY (user_id) REFERENCES users(id)
);

-- -------------------------------------------------------
-- SUBSCRIPTIONS & LICENSES
-- -------------------------------------------------------

CREATE TABLE user_subscriptions (
    id         INT          IDENTITY(1,1) PRIMARY KEY,
    user_id    UNIQUEIDENTIFIER NOT NULL,
    plan_id    INT          NOT NULL,
    card_type  NVARCHAR(5)  NOT NULL CHECK (card_type IN ('SC1', 'SC2')),
    start_date DATE         NOT NULL,
    end_date   DATE,
    is_active  BIT          NOT NULL DEFAULT 1,
    CONSTRAINT fk_user_subscriptions_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_user_subscriptions_plan FOREIGN KEY (plan_id) REFERENCES subscription_plans(id)
);

CREATE TABLE institution_licenses (
    id             INT          IDENTITY(1,1) PRIMARY KEY,
    institution_id UNIQUEIDENTIFIER NOT NULL,
    billing_type   NVARCHAR(10) NOT NULL CHECK (billing_type IN ('monthly', 'quarterly', 'semiannual', 'annual')),
    start_date     DATE         NOT NULL,
    end_date       DATE,
    is_active      BIT          NOT NULL DEFAULT 1,
    CONSTRAINT fk_institution_licenses_institution FOREIGN KEY (institution_id) REFERENCES institutions(id)
);

-- -------------------------------------------------------
-- ACCESS CONTROL
-- -------------------------------------------------------

CREATE TABLE access_requests (
    id           INT           IDENTITY(1,1) PRIMARY KEY,
    user_id      UNIQUEIDENTIFIER NOT NULL,
    doctor_id    UNIQUEIDENTIFIER NOT NULL,
    requested_at DATETIME2     NOT NULL DEFAULT GETDATE(),
    approved_at  DATETIME2,
    expires_at   DATETIME2,
    status       NVARCHAR(20)  NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'revoked')),
    is_emergency BIT           NOT NULL DEFAULT 0,
    access_code  NVARCHAR(100),
    CONSTRAINT fk_access_requests_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_access_requests_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);
GO

-- Rule: an access request can only be flagged is_emergency = 1 if the
-- patient has pre-authorised emergency access (users.emergency_access_code = 1)
CREATE TRIGGER trg_access_requests_emergency_consent
ON access_requests
AFTER INSERT, UPDATE
AS
BEGIN
    SET NOCOUNT ON;
    IF EXISTS (
        SELECT 1
        FROM inserted i
        JOIN users u ON u.id = i.user_id
        WHERE i.is_emergency = 1 AND u.emergency_access_code = 0
    )
    BEGIN
        RAISERROR ('access_requests.is_emergency = 1 requires users.emergency_access_code = 1', 16, 1);
        ROLLBACK TRANSACTION;
    END
END;
GO

-- -------------------------------------------------------
-- FILES
-- -------------------------------------------------------

CREATE TABLE medical_files (
    id          INT            IDENTITY(1,1) PRIMARY KEY,
    user_id     UNIQUEIDENTIFIER NOT NULL,
    file_name   NVARCHAR(255)  NOT NULL,
    file_type   NVARCHAR(100),
    file_path   NVARCHAR(1000) NOT NULL,
    uploaded_by UNIQUEIDENTIFIER,
    uploaded_at DATETIME2      NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_medical_files_user   FOREIGN KEY (user_id)     REFERENCES users(id),
    CONSTRAINT fk_medical_files_doctor FOREIGN KEY (uploaded_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- MEDICAL HISTORY
-- -------------------------------------------------------

CREATE TABLE surgical_history (
    id             INT           IDENTITY(1,1) PRIMARY KEY,
    user_id        UNIQUEIDENTIFIER NOT NULL,
    surgery_name   NVARCHAR(255) NOT NULL,
    surgery_date   DATE,
    location       NVARCHAR(255),
    notes          NVARCHAR(MAX),
    report_file_id INT,
    added_by       UNIQUEIDENTIFIER,
    is_active      BIT           NOT NULL DEFAULT 1,
    created_at     DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_surgical_history_user   FOREIGN KEY (user_id)        REFERENCES users(id),
    CONSTRAINT fk_surgical_history_file   FOREIGN KEY (report_file_id) REFERENCES medical_files(id),
    CONSTRAINT fk_surgical_history_doctor FOREIGN KEY (added_by)       REFERENCES doctors(id)
);

CREATE TABLE chronic_medications (
    id               INT           IDENTITY(1,1) PRIMARY KEY,
    user_id          UNIQUEIDENTIFIER NOT NULL,
    active_substance NVARCHAR(255) NOT NULL,
    dose             NVARCHAR(100),
    posology         NVARCHAR(255),
    start_date       DATE,
    end_date         DATE,
    prescribed_by    UNIQUEIDENTIFIER,
    is_active        BIT           NOT NULL DEFAULT 1,
    created_at       DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_chronic_medications_user   FOREIGN KEY (user_id)      REFERENCES users(id),
    CONSTRAINT fk_chronic_medications_doctor FOREIGN KEY (prescribed_by) REFERENCES doctors(id)
);

CREATE TABLE drug_allergies (
    id               INT           IDENTITY(1,1) PRIMARY KEY,
    user_id          UNIQUEIDENTIFIER NOT NULL,
    active_substance NVARCHAR(255) NOT NULL,
    allergic_reaction NVARCHAR(500),
    severity         NVARCHAR(20)  CHECK (severity IN ('mild', 'moderate', 'severe')),
    created_at       DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_drug_allergies_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE family_history (
    id            INT           IDENTITY(1,1) PRIMARY KEY,
    user_id       UNIQUEIDENTIFIER NOT NULL,
    condition     NVARCHAR(50)  NOT NULL CHECK (condition IN ('cardiovascular', 'cancer', 'autoimmune', 'genetic', 'ophthalmic', 'psychological', 'consanguinity', 'other')),
    has_condition BIT           NOT NULL DEFAULT 0,
    kinship_degree NVARCHAR(100),
    notes         NVARCHAR(MAX),
    CONSTRAINT fk_family_history_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_pathologies (
    id           INT          IDENTITY(1,1) PRIMARY KEY,
    user_id      UNIQUEIDENTIFIER NOT NULL,
    icpc2_id     INT          NOT NULL,
    type         NVARCHAR(10) NOT NULL CHECK (type IN ('active', 'passive')),
    diagnosed_at DATE,
    notes        NVARCHAR(MAX),
    added_by     UNIQUEIDENTIFIER,
    CONSTRAINT fk_user_pathologies_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_user_pathologies_icpc2  FOREIGN KEY (icpc2_id) REFERENCES icpc2_codes(id),
    CONSTRAINT fk_user_pathologies_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE user_specialty_followups (
    id           INT           IDENTITY(1,1) PRIMARY KEY,
    user_id      UNIQUEIDENTIFIER NOT NULL,
    specialty_id INT           NOT NULL,
    institution  NVARCHAR(255),
    start_date   DATE,
    notes        NVARCHAR(MAX),
    CONSTRAINT fk_user_specialty_followups_user      FOREIGN KEY (user_id)      REFERENCES users(id),
    CONSTRAINT fk_user_specialty_followups_specialty FOREIGN KEY (specialty_id) REFERENCES medical_specialties(id)
);

-- -------------------------------------------------------
-- EXAMS (MCDTS)
-- -------------------------------------------------------

CREATE TABLE analytical_exams (
    id         INT           IDENTITY(1,1) PRIMARY KEY,
    user_id    UNIQUEIDENTIFIER NOT NULL,
    exam_date  DATE          NOT NULL,
    laboratory NVARCHAR(255),
    file_id    INT,
    notes      NVARCHAR(MAX),
    added_by   UNIQUEIDENTIFIER,
    is_active  BIT           NOT NULL DEFAULT 1,
    created_at DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_analytical_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_analytical_exams_file   FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    CONSTRAINT fk_analytical_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE analytical_exam_parameters (
    id             INT           IDENTITY(1,1) PRIMARY KEY,
    exam_id        INT           NOT NULL,
    parameter_name NVARCHAR(255) NOT NULL,
    value          DECIMAL(18,6),
    unit           NVARCHAR(50),
    reference_min  DECIMAL(18,6),
    reference_max  DECIMAL(18,6),
    is_abnormal    BIT           NOT NULL DEFAULT 0,
    CONSTRAINT fk_analytical_exam_parameters_exam FOREIGN KEY (exam_id) REFERENCES analytical_exams(id)
);

CREATE TABLE imaging_exams (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    user_id     UNIQUEIDENTIFIER NOT NULL,
    exam_type   NVARCHAR(100) NOT NULL,
    body_area   NVARCHAR(100),
    exam_date   DATE          NOT NULL,
    institution NVARCHAR(255),
    file_id     INT,
    report_text NVARCHAR(MAX),
    added_by    UNIQUEIDENTIFIER,
    is_active   BIT           NOT NULL DEFAULT 1,
    created_at  DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_imaging_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_imaging_exams_file   FOREIGN KEY (file_id)  REFERENCES medical_files(id),
    CONSTRAINT fk_imaging_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

CREATE TABLE optometry_exams (
    id              INT           IDENTITY(1,1) PRIMARY KEY,
    user_id         UNIQUEIDENTIFIER NOT NULL,
    exam_date       DATE          NOT NULL,
    right_sphere    DECIMAL(5,2),
    right_cylinder  DECIMAL(5,2),
    right_axis      INT,
    left_sphere     DECIMAL(5,2),
    left_cylinder   DECIMAL(5,2),
    left_axis       INT,
    disease_report  NVARCHAR(MAX),
    added_by        UNIQUEIDENTIFIER,
    is_active       BIT           NOT NULL DEFAULT 1,
    created_at      DATETIME2     NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_optometry_exams_user   FOREIGN KEY (user_id)  REFERENCES users(id),
    CONSTRAINT fk_optometry_exams_doctor FOREIGN KEY (added_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VACCINATIONS
-- -------------------------------------------------------

CREATE TABLE user_vaccinations (
    id             INT           IDENTITY(1,1) PRIMARY KEY,
    user_id        UNIQUEIDENTIFIER NOT NULL,
    vaccine_id     INT           NOT NULL,
    dose_number    NVARCHAR(20),
    administered_at DATE,
    next_due_date  DATE,
    batch_number   NVARCHAR(100),
    institution    NVARCHAR(255),
    notes          NVARCHAR(MAX),
    added_by       UNIQUEIDENTIFIER,
    CONSTRAINT fk_user_vaccinations_user    FOREIGN KEY (user_id)    REFERENCES users(id),
    CONSTRAINT fk_user_vaccinations_vaccine FOREIGN KEY (vaccine_id) REFERENCES vaccines(id),
    CONSTRAINT fk_user_vaccinations_doctor  FOREIGN KEY (added_by)   REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- HEALTH HABITS (consolidated)
-- details (JSON): type-specific fields
--   alcohol  -> { consumes, alcohol_type, in_detox, audit_c_score, audit_score }
--   tobacco  -> { consumes, cigarettes_per_day, years_consumption, pack_years, fagerstrom_score, richmond_score }
--   drugs    -> { drug_name, quantity }
--   gambling -> { game_name }
--   physical_activity -> { activity }
-- -------------------------------------------------------

CREATE TABLE health_habits (
    id         INT           IDENTITY(1,1) PRIMARY KEY,
    user_id    UNIQUEIDENTIFIER NOT NULL,
    type_id    INT           NOT NULL,
    name       NVARCHAR(255),
    consumes   BIT,
    frequency  NVARCHAR(100),
    quantity   NVARCHAR(100),
    start_date DATE,
    updated_at DATETIME2     NOT NULL DEFAULT GETDATE(),
    details    NVARCHAR(MAX),
    CONSTRAINT fk_health_habits_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_health_habits_type FOREIGN KEY (type_id) REFERENCES habit_types(id)
);

-- -------------------------------------------------------
-- DOCTOR NOTES & FLAGS
-- note_text is stored encrypted (application-layer encryption)
-- -------------------------------------------------------

CREATE TABLE doctor_notes (
    id        INT           IDENTITY(1,1) PRIMARY KEY,
    user_id   UNIQUEIDENTIFIER NOT NULL,
    doctor_id UNIQUEIDENTIFIER NOT NULL,
    section   NVARCHAR(50)  NOT NULL CHECK (section IN ('identification', 'medical_info', 'mcdts', 'habits', 'history', 'other')),
    note_text VARBINARY(MAX),
    created_at DATETIME2    NOT NULL DEFAULT GETDATE(),
    updated_at DATETIME2    NOT NULL DEFAULT GETDATE(),
    CONSTRAINT fk_doctor_notes_user   FOREIGN KEY (user_id)   REFERENCES users(id),
    CONSTRAINT fk_doctor_notes_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id)
);

CREATE TABLE pending_review_flags (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    user_id     UNIQUEIDENTIFIER NOT NULL,
    section     NVARCHAR(100) NOT NULL,
    created_at  DATETIME2     NOT NULL DEFAULT GETDATE(),
    reviewed_at DATETIME2,
    reviewed_by UNIQUEIDENTIFIER,
    CONSTRAINT fk_pending_review_flags_user   FOREIGN KEY (user_id)     REFERENCES users(id),
    CONSTRAINT fk_pending_review_flags_doctor FOREIGN KEY (reviewed_by) REFERENCES doctors(id)
);

-- -------------------------------------------------------
-- VERSIONING
-- -------------------------------------------------------

CREATE TABLE schema_versions (
    id          INT           IDENTITY(1,1) PRIMARY KEY,
    version     NVARCHAR(20)  NOT NULL,
    description NVARCHAR(255),
    script      NVARCHAR(255),
    applied_at  DATETIME2     NOT NULL DEFAULT GETDATE(),
    applied_by  NVARCHAR(100),
    checksum    NVARCHAR(64),
    success     BIT           NOT NULL DEFAULT 1
);

CREATE TABLE app_versions (
    id           INT           IDENTITY(1,1) PRIMARY KEY,
    version      NVARCHAR(20)  NOT NULL,
    release_date DATE,
    description  NVARCHAR(255),
    deployed_at  DATETIME2     NOT NULL DEFAULT GETDATE(),
    deployed_by  NVARCHAR(100),
    environment  NVARCHAR(20)  NOT NULL CHECK (environment IN ('dev', 'staging', 'prod')),
    is_current   BIT           NOT NULL DEFAULT 0
);
