-- =============================================================
-- MediVault -- Test Data (Portuguese)
-- Compatible with SQL Server, SQLite, MySQL, PostgreSQL
-- Note: booleans use 1/0 (SQL Server/SQLite) — for PostgreSQL
--       replace with TRUE/FALSE; MySQL accepts both.
-- Note: users.id, doctors.id and institutions.id are fixed GUIDs
--       (literals), to keep relationships deterministic across
--       dialects. Normally generated by the application (Guid.NewGuid()).
-- =============================================================

-- -------------------------------------------------------
-- SUBSCRIPTION_PLANS
-- -------------------------------------------------------
INSERT INTO subscription_plans (name, storage_limit_mb, price_annual, price_monthly) VALUES
('basic',   512,  49.99,  4.99),
('medium',  2048, 99.99,  9.99),
('premium', 5120, 199.99, 19.99);

-- -------------------------------------------------------
-- INSTITUTIONS
-- id: fixed GUID (10000000-0000-0000-0000-00000000000X)
-- -------------------------------------------------------
INSERT INTO institutions (id, name, type, address, phone, is_active) VALUES
('10000000-0000-0000-0000-000000000001', 'Hospital de Santa Maria',        'hospital', 'Av. Professor Egas Moniz, Lisboa',      '217 805 000', 1),
('10000000-0000-0000-0000-000000000002', 'Clínica CUF Descobertas',        'clinic',   'R. Mário Botas, Lisboa',                '210 025 200', 1),
('10000000-0000-0000-0000-000000000003', 'Laboratório Germano de Sousa',   'lab',      'Av. Liberdade 110, Lisboa',             '213 185 100', 1),
('10000000-0000-0000-0000-000000000004', 'Centro Hospitalar do Porto',     'hospital', 'Largo Prof. Abel Salazar, Porto',       '222 077 500', 1);

-- -------------------------------------------------------
-- VACCINES (National Vaccination Programme - PNV)
-- -------------------------------------------------------
INSERT INTO vaccines (name, description) VALUES
('BCG',   'Vacina contra a tuberculose'),
('VHB',   'Vacina contra a hepatite B'),
('DTPa',  'Vacina contra difteria, tétano e tosse convulsa'),
('VIP',   'Vacina inativada contra a poliomielite'),
('Hib',   'Vacina contra Haemophilus influenzae tipo b'),
('MenC',  'Vacina contra meningite C'),
('VASPR', 'Vacina contra sarampo, parotidite e rubéola'),
('VVZ',   'Vacina contra a varicela'),
('VHA',   'Vacina contra a hepatite A'),
('Flu',   'Vacina contra a gripe (dose anual)');

-- -------------------------------------------------------
-- ICPC2_CODES (sample of relevant codes)
-- -------------------------------------------------------
INSERT INTO icpc2_codes (code, description, chapter) VALUES
('K86', 'Hipertensão sem complicações',       'K - Circulatório'),
('K87', 'Hipertensão com complicações',        'K - Circulatório'),
('T90', 'Diabetes mellitus tipo 1',            'T - Endócrino/Metabólico/Nutricional'),
('T89', 'Diabetes mellitus tipo 2',            'T - Endócrino/Metabólico/Nutricional'),
('R05', 'Tosse',                               'R - Respiratório'),
('R74', 'Infecção respiratória alta',          'R - Respiratório'),
('A97', 'Sem doença',                          'A - Geral/Inespecífico'),
('L87', 'Espondilartrose',                     'L - Músculo-esquelético'),
('P76', 'Depressão',                           'P - Psicológico'),
('D73', 'Gastroenterite',                      'D - Digestivo');

-- -------------------------------------------------------
-- MEDICAL_SPECIALTIES
-- -------------------------------------------------------
INSERT INTO medical_specialties (name) VALUES
('Cardiologia'),
('Oncologia'),
('Neurologia'),
('Ortopedia'),
('Oftalmologia'),
('Gastrenterologia'),
('Endocrinologia'),
('Pneumologia'),
('Psiquiatria'),
('Medicina Interna');

-- -------------------------------------------------------
-- GENDERS (config table — code matches the former CHECK constraint)
-- id 1=M, 2=F, 3=Other
-- -------------------------------------------------------
INSERT INTO genders (code, description) VALUES
('M',     'Masculino'),
('F',     'Feminino'),
('Other', 'Outro');

-- -------------------------------------------------------
-- HABIT_TYPES (config table — code matches the former CHECK constraint)
-- id 1=alcohol, 2=tobacco, 3=drugs, 4=gambling, 5=physical_activity
-- -------------------------------------------------------
INSERT INTO habit_types (code, description) VALUES
('alcohol',           'Consumo de álcool'),
('tobacco',           'Consumo de tabaco'),
('drugs',             'Consumo de drogas ilícitas'),
('gambling',          'Jogo / apostas'),
('physical_activity', 'Atividade física');

-- -------------------------------------------------------
-- RELATIONSHIP_TYPES (config table — code matches the former CHECK constraint)
-- id 1=parent, 2=legal_guardian, 3=tutor, 4=other
-- -------------------------------------------------------
INSERT INTO relationship_types (code, description) VALUES
('parent',         'Pai / mãe'),
('legal_guardian', 'Tutor legal nomeado por tribunal (pessoa incapacitada)'),
('tutor',          'Tutor de menor sem tutela parental'),
('other',          'Outro tipo de responsável');

-- -------------------------------------------------------
-- COUNTRIES (config table)
-- Full ISO 3166-1 list (alpha-3 code), sorted alphabetically
-- by the Portuguese name.
-- Used in the seeds below: Portugal id=184, Brasil id=30, Espanha id=66
-- -------------------------------------------------------
INSERT INTO countries (code, name) VALUES
('AFG', 'Afeganistão'),
('ZAF', 'África do Sul'),
('ALB', 'Albânia'),
('DEU', 'Alemanha'),
('AND', 'Andorra'),
('AGO', 'Angola'),
('AIA', 'Anguila'),
('ATA', 'Antártida'),
('ATG', 'Antígua e Barbuda'),
('SAU', 'Arábia Saudita'),
('DZA', 'Argélia'),
('ARG', 'Argentina'),
('ARM', 'Armênia'),
('ABW', 'Aruba'),
('AUS', 'Austrália'),
('AUT', 'Áustria'),
('AZE', 'Azerbaijão'),
('BHS', 'Bahamas'),
('BGD', 'Bangladexe'),
('BRB', 'Barbados'),
('BHR', 'Barém'),
('BEL', 'Bélgica'),
('BLZ', 'Belize'),
('BEN', 'Benim'),
('BMU', 'Bermudas'),
('BLR', 'Bielorrússia'),
('BOL', 'Bolívia'),
('BIH', 'Bósnia e Herzegovina'),
('BWA', 'Botsuana'),
('BRA', 'Brasil'),
('BRN', 'Brunei'),
('BGR', 'Bulgária'),
('BFA', 'Burquina Fasso'),
('BDI', 'Burundi'),
('BTN', 'Butão'),
('CPV', 'Cabo Verde'),
('CMR', 'Camarões'),
('KHM', 'Camboja'),
('CAN', 'Canadá'),
('QAT', 'Catar'),
('KAZ', 'Cazaquistão'),
('TCD', 'Chade'),
('CZE', 'Chéquia'),
('CHL', 'Chile'),
('CHN', 'China'),
('CYP', 'Chipre'),
('COL', 'Colômbia'),
('COM', 'Comores'),
('PRK', 'Coreia do Norte'),
('KOR', 'Coreia do Sul'),
('CIV', 'Costa do Marfim'),
('CRI', 'Costa Rica'),
('HRV', 'Croácia'),
('CUB', 'Cuba'),
('CUW', 'Curaçau'),
('DNK', 'Dinamarca'),
('DJI', 'Djibuti'),
('DMA', 'Dominica'),
('EGY', 'Egito'),
('SLV', 'El Salvador'),
('ARE', 'Emirados Árabes Unidos'),
('ECU', 'Equador'),
('ERI', 'Eritreia'),
('SVK', 'Eslováquia'),
('SVN', 'Eslovênia'),
('ESP', 'Espanha'),
('SWZ', 'Essuatíni'),
('FSM', 'Estados Federados da Micronésia'),
('USA', 'Estados Unidos'),
('EST', 'Estónia'),
('SJM', 'Esvalbarde e Jan Mayen'),
('ETH', 'Etiópia'),
('FJI', 'Fiji'),
('PHL', 'Filipinas'),
('FIN', 'Finlândia'),
('FRA', 'França'),
('GAB', 'Gabão'),
('GMB', 'Gâmbia'),
('GHA', 'Gana'),
('GEO', 'Geórgia'),
('GIB', 'Gibraltar'),
('GRD', 'Granada'),
('GRC', 'Grécia'),
('GRL', 'Gronelândia'),
('GLP', 'Guadalupe'),
('GUM', 'Guam'),
('GTM', 'Guatemala'),
('GGY', 'Guernsey'),
('GUY', 'Guiana'),
('GUF', 'Guiana Francesa'),
('GIN', 'Guiné'),
('GNQ', 'Guiné Equatorial'),
('GNB', 'Guiné-Bissau'),
('HTI', 'Haiti'),
('HND', 'Honduras'),
('HKG', 'Hong Kong'),
('HUN', 'Hungria'),
('YEM', 'Iêmen'),
('BVT', 'Ilha Bouvet'),
('IMN', 'Ilha de Man'),
('CXR', 'Ilha do Natal'),
('HMD', 'Ilha Heard e Ilhas McDonald'),
('NFK', 'Ilha Norfolk'),
('ALA', 'Ilhas Åland'),
('CYM', 'Ilhas Caimã'),
('CCK', 'Ilhas Cocos (Keeling)'),
('COK', 'Ilhas Cook'),
('FRO', 'Ilhas Feroé'),
('SGS', 'Ilhas Geórgia do Sul e Sandwich do Sul'),
('FLK', 'Ilhas Malvinas'),
('MHL', 'Ilhas Marshall'),
('MUS', 'Ilhas Maurícias'),
('UMI', 'Ilhas Menores Distantes dos Estados Unidos'),
('SLB', 'Ilhas Salomão'),
('VIR', 'Ilhas Virgens Americanas'),
('VGB', 'Ilhas Virgens Britânicas'),
('IND', 'Índia'),
('IDN', 'Indonésia'),
('IRN', 'Irão'),
('IRQ', 'Iraque'),
('IRL', 'Irlanda'),
('ISL', 'Islândia'),
('ISR', 'Israel'),
('ITA', 'Itália'),
('JAM', 'Jamaica'),
('JPN', 'Japão'),
('JEY', 'Jersey'),
('JOR', 'Jordânia'),
('KWT', 'Kuwait'),
('LAO', 'Laos'),
('LSO', 'Lesoto'),
('LVA', 'Letónia'),
('LBN', 'Líbano'),
('LBR', 'Libéria'),
('LBY', 'Líbia'),
('LIE', 'Listenstaine'),
('LTU', 'Lituânia'),
('LUX', 'Luxemburgo'),
('MAC', 'Macau'),
('MKD', 'Macedônia do Norte'),
('MDG', 'Madagáscar'),
('MYT', 'Maiote'),
('MYS', 'Malásia'),
('MWI', 'Maláui'),
('MDV', 'Maldivas'),
('MLI', 'Mali'),
('MLT', 'Malta'),
('MNP', 'Marianas Setentrionais'),
('MAR', 'Marrocos'),
('MTQ', 'Martinica'),
('MRT', 'Mauritânia'),
('MEX', 'México'),
('MOZ', 'Moçambique'),
('MDA', 'Moldávia'),
('MCO', 'Mónaco'),
('MNG', 'Mongólia'),
('MSR', 'Monserrate'),
('MNE', 'Montenegro'),
('MMR', 'Myanmar'),
('NAM', 'Namíbia'),
('NRU', 'Nauru'),
('NPL', 'Nepal'),
('NIC', 'Nicarágua'),
('NER', 'Níger'),
('NGA', 'Nigéria'),
('NIU', 'Niue'),
('NOR', 'Noruega'),
('NCL', 'Nova Caledônia'),
('NZL', 'Nova Zelândia'),
('OMN', 'Omã'),
('NLD', 'Países Baixos'),
('BES', 'Países Baixos Caribenhos'),
('PLW', 'Palau'),
('PSE', 'Palestina'),
('PAN', 'Panamá'),
('PNG', 'Papua-Nova Guiné'),
('PAK', 'Paquistão'),
('PRY', 'Paraguai'),
('PER', 'Peru'),
('PCN', 'Pitcairn'),
('PYF', 'Polinésia Francesa'),
('POL', 'Polónia'),
('PRI', 'Porto Rico'),
('PRT', 'Portugal'),
('KEN', 'Quênia'),
('KGZ', 'Quirguistão'),
('KIR', 'Quiribáti'),
('GBR', 'Reino Unido'),
('CAF', 'República Centro-Africana'),
('COD', 'República Democrática do Congo'),
('COG', 'República do Congo'),
('DOM', 'República Dominicana'),
('REU', 'Reunião'),
('ROU', 'Roménia'),
('RWA', 'Ruanda'),
('RUS', 'Rússia'),
('ESH', 'Saara Ocidental'),
('WSM', 'Samoa'),
('ASM', 'Samoa Americana'),
('SMR', 'San Marino'),
('SHN', 'Santa Helena, Ascensão e Tristão da Cunha'),
('LCA', 'Santa Lúcia'),
('BLM', 'São Bartolomeu'),
('KNA', 'São Cristóvão e Neves'),
('MAF', 'São Martinho'),
('SXM', 'São Martinho'),
('SPM', 'São Pedro e Miquelão'),
('STP', 'São Tomé e Príncipe'),
('VCT', 'São Vicente e Granadinas'),
('SYC', 'Seicheles'),
('SEN', 'Senegal'),
('LKA', 'Seri Lanca'),
('SLE', 'Serra Leoa'),
('SRB', 'Sérvia'),
('SGP', 'Singapura'),
('SYR', 'Síria'),
('SOM', 'Somália'),
('SDN', 'Sudão'),
('SSD', 'Sudão do Sul'),
('SWE', 'Suécia'),
('CHE', 'Suíça'),
('SUR', 'Suriname'),
('THA', 'Tailândia'),
('TWN', 'Taiwan'),
('TJK', 'Tajiquistão'),
('TZA', 'Tanzânia'),
('ATF', 'Terras Austrais e Antárticas Francesas'),
('IOT', 'Território Britânico do Oceano Índico'),
('TLS', 'Timor-Leste'),
('TGO', 'Togo'),
('TON', 'Tonga'),
('TKL', 'Toquelau'),
('TTO', 'Trinidad e Tobago'),
('TUN', 'Tunísia'),
('TCA', 'Turcas e Caicos'),
('TKM', 'Turcomenistão'),
('TUR', 'Turquia'),
('TUV', 'Tuvalu'),
('UKR', 'Ucrânia'),
('UGA', 'Uganda'),
('URY', 'Uruguai'),
('UZB', 'Uzbequistão'),
('VUT', 'Vanuatu'),
('VAT', 'Vaticano'),
('VEN', 'Venezuela'),
('VNM', 'Vietname'),
('WLF', 'Wallis e Futuna'),
('ZMB', 'Zâmbia'),
('ZWE', 'Zimbábue');

-- -------------------------------------------------------
-- USERS (Portuguese patients)
-- id: fixed GUID (30000000-0000-0000-0000-00000000000X)
-- sex_id references GENDERS.id; nationality_id references COUNTRIES.id
-- (184=Portugal, 30=Brasil)
-- -------------------------------------------------------
INSERT INTO users (id, utent_number, fiscal_number, citizen_number, email, password_hash, first_name, last_name, birthday, biological_gender, sex_id, nationality_id, marital_status, blood_type, accepts_transfusion, accepts_resuscitation, emergency_access_code, is_dependent, profession, phone, is_active, card_active) VALUES
('30000000-0000-0000-0000-000000000001', '123456789', '123456789', '12345678', 'joao.silva@email.pt',      '$2b$12$hash1', 'João',   'Silva',     '1985-03-12', 'M', 1, 184, 'Casado',    'A+',  1, 1, 0, 0, 'Engenheiro', '912 345 678', 1, 1),
('30000000-0000-0000-0000-000000000002', '234567890', '234567890', '23456789', 'ana.santos@email.pt',      '$2b$12$hash2', 'Ana',    'Santos',    '1990-07-24', 'F', 2, 184, 'Solteira',  'O+',  1, 1, 1, 0, 'Médica',     '913 456 789', 1, 1),
('30000000-0000-0000-0000-000000000003', '345678901', '345678901', '34567890', 'miguel.ferreira@email.pt', '$2b$12$hash3', 'Miguel', 'Ferreira',  '1978-11-05', 'M', 1, 30,  'Divorciado','B-',  0, 1, 1, 0, 'Professor',  '914 567 890', 1, 1),
('30000000-0000-0000-0000-000000000004', '456789012', '456789012', '45678901', 'maria.pereira@email.pt',   '$2b$12$hash4', 'Maria',  'Pereira',   '1965-02-18', 'F', 2, 184, 'Viúva',     'AB+', 1, 0, 1, 0, 'Reformada',  '915 678 901', 1, 1),
('30000000-0000-0000-0000-000000000005', '567890123', '567890123', '56789012', 'pedro.costa@email.pt',     '$2b$12$hash5', 'Pedro',  'Costa',     '2005-09-30', 'M', 1, 184, 'Solteiro',  'O-',  1, 1, 1, 1, 'Estudante',  '916 789 012', 1, 1),
-- test accounts (team members — patient side; see DOCTORS below for their doctor-side accounts)
-- all 14 test accounts (patient + doctor) share the password "password123" for QA convenience
('30000000-0000-0000-0000-000000000006', '678901234', '678901234', '67890123', 'braulio.batista@email.pt',   '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Braulio', 'Batista',  '1990-01-15', 'M', 1, 184, 'Solteiro', 'A+',  1, 1, 1, 0, 'Engenheiro de Software', '917 000 001', 1, 1),
('30000000-0000-0000-0000-000000000007', '789012345', '789012345', '78901234', 'monica.cerquido@email.pt',   '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Mónica',  'Cerquido', '1988-05-22', 'F', 2, 184, 'Casada',   'B+',  1, 1, 1, 0, 'Product Owner',          '917 000 002', 1, 1),
('30000000-0000-0000-0000-000000000008', '890123456', '890123456', '89012345', 'cesar.campinho@email.pt',    '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'César',   'Campinho', '1992-09-10', 'M', 1, 184, 'Solteiro', 'O+',  1, 1, 1, 0, 'Engenheiro de Software', '917 000 003', 1, 1),
('30000000-0000-0000-0000-000000000009', '901234567', '901234567', '90123456', 'tiago.faria@email.pt',       '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Tiago',   'Faria',    '1995-03-03', 'M', 1, 184, 'Solteiro', 'AB+', 1, 1, 1, 0, 'Designer',               '917 000 004', 1, 1),
('30000000-0000-0000-0000-000000000010', '112233445', '112233445', '11223344', 'joaquim.oliveira@email.pt',  '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Joaquim', 'Oliveira', '1970-12-01', 'M', 1, 184, 'Casado',   'A-',  1, 1, 1, 0, 'Consultor',              '917 000 005', 1, 1),
('30000000-0000-0000-0000-000000000011', '223344556', '223344556', '22334455', 'maria.costa@email.pt',       '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Maria',   'Costa',    '1983-06-18', 'F', 2, 184, 'Casada',   'O-',  1, 1, 1, 0, 'Enfermeira',             '917 000 006', 1, 1),
('30000000-0000-0000-0000-000000000012', '334455667', '334455667', '33445566', 'diana.almeida@email.pt',     '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Diana',   'Almeida',  '1998-11-27', 'F', 2, 184, 'Solteira', 'B-',  1, 1, 1, 0, 'Estudante',              '917 000 007', 1, 1);

-- -------------------------------------------------------
-- DOCTORS
-- id: fixed GUID (20000000-0000-0000-0000-00000000000X)
-- institution_id references INSTITUTIONS.id; nationality_id references COUNTRIES.id
-- -------------------------------------------------------
-- nationality_id references COUNTRIES.id (184=Portugal, 66=Espanha)
INSERT INTO doctors (id, ordem_medicos_id, first_name, last_name, email, password_hash, speciality, institution_id, nationality_id, is_active) VALUES
('20000000-0000-0000-0000-000000000001', 'OM-12345', 'Carlos',  'Rodrigues', 'carlos.rodrigues@hsm.pt', '$2b$12$dhash1', 'Cardiologia',    '10000000-0000-0000-0000-000000000001', 184, 1),
('20000000-0000-0000-0000-000000000002', 'OM-23456', 'Sofia',   'Martins',   'sofia.martins@cuf.pt',    '$2b$12$dhash2', 'Medicina Geral', '10000000-0000-0000-0000-000000000002', 184, 1),
('20000000-0000-0000-0000-000000000003', 'OM-34567', 'António', 'Carvalho',  'antonio.carvalho@chp.pt', '$2b$12$dhash3', 'Neurologia',     '10000000-0000-0000-0000-000000000004', 184, 1),
('20000000-0000-0000-0000-000000000004', 'OM-45678', 'Filipa',  'Alves',     'filipa.alves@hsm.pt',     '$2b$12$dhash4', 'Endocrinologia', '10000000-0000-0000-0000-000000000001', 66,  1),
-- test accounts (team members — doctor side; same people as USERS above, different login/password)
('20000000-0000-0000-0000-000000000005', 'OM-56789', 'Braulio', 'Batista',  'braulio.batista@hsm.pt',  '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Pediatria',      '10000000-0000-0000-0000-000000000001', 184, 1),
('20000000-0000-0000-0000-000000000006', 'OM-67890', 'Mónica',  'Cerquido', 'monica.cerquido@cuf.pt',  '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Ginecologia',    '10000000-0000-0000-0000-000000000002', 184, 1),
('20000000-0000-0000-0000-000000000007', 'OM-78901', 'César',   'Campinho', 'cesar.campinho@chp.pt',   '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Ortopedia',      '10000000-0000-0000-0000-000000000004', 184, 1),
('20000000-0000-0000-0000-000000000008', 'OM-89012', 'Tiago',   'Faria',    'tiago.faria@hsm.pt',      '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Dermatologia',   '10000000-0000-0000-0000-000000000001', 184, 1),
('20000000-0000-0000-0000-000000000009', 'OM-90123', 'Joaquim', 'Oliveira', 'joaquim.oliveira@cuf.pt', '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Psiquiatria',    '10000000-0000-0000-0000-000000000002', 184, 1),
('20000000-0000-0000-0000-000000000010', 'OM-10234', 'Maria',   'Costa',    'maria.costa@chp.pt',      '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Oftalmologia',   '10000000-0000-0000-0000-000000000004', 184, 1),
('20000000-0000-0000-0000-000000000011', 'OM-11234', 'Diana',   'Almeida',  'diana.almeida@hsm.pt',    '$2b$12$62zUab6NmnTBVrCmarJo9OI9nmPVgTQNaGdZ0VMbtRSDH92RLwNuW', 'Clínica Geral',  '10000000-0000-0000-0000-000000000001', 184, 1);

-- -------------------------------------------------------
-- USER_ADDRESSES
-- -------------------------------------------------------
INSERT INTO user_addresses (user_id, street, city, postal_code, country, is_primary) VALUES
('30000000-0000-0000-0000-000000000001', 'Rua da Liberdade, 45 2º Dto',  'Lisboa', '1250-096', 'Portugal', 1),
('30000000-0000-0000-0000-000000000002', 'Av. da República, 120 3º Esq', 'Lisboa', '1050-187', 'Portugal', 1),
('30000000-0000-0000-0000-000000000003', 'R. de Santa Catarina, 78',     'Porto',  '4000-447', 'Portugal', 1),
('30000000-0000-0000-0000-000000000004', 'Largo do Chiado, 5 1º',        'Lisboa', '1200-108', 'Portugal', 1),
('30000000-0000-0000-0000-000000000005', 'R. Direita, 12',               'Braga',  '4700-223', 'Portugal', 1);

-- -------------------------------------------------------
-- EMERGENCY_CONTACTS
-- -------------------------------------------------------
INSERT INTO emergency_contacts (user_id, type, name, phone, address) VALUES
('30000000-0000-0000-0000-000000000001', 'emergency', 'Marta Silva',    '917 111 222', 'Rua da Liberdade, 45 2º Dto, Lisboa'),
('30000000-0000-0000-0000-000000000002', 'emergency', 'Rui Santos',     '918 222 333', 'Av. da República, 120 3º Esq, Lisboa'),
('30000000-0000-0000-0000-000000000003', 'emergency', 'Luísa Ferreira', '919 333 444', 'R. de Santa Catarina, 78, Porto'),
('30000000-0000-0000-0000-000000000004', 'emergency', 'José Pereira',   '920 444 555', 'Largo do Chiado, 5 1º, Lisboa'),
('30000000-0000-0000-0000-000000000005', 'tutor',     'Beatriz Costa',  '921 555 666', 'R. Direita, 12, Braga');

-- -------------------------------------------------------
-- FAMILY_GUARDIANSHIPS (Pedro Costa is_dependent=1; parents divorced, both keep guardianship)
-- -------------------------------------------------------
-- relationship_type_id: 1=parent (see RELATIONSHIP_TYPES above)
INSERT INTO family_guardianships (guardian_user_id, dependent_user_id, relationship_type_id, status, is_active) VALUES
('30000000-0000-0000-0000-000000000004', '30000000-0000-0000-0000-000000000005', 1, 'approved', 1),
('30000000-0000-0000-0000-000000000003', '30000000-0000-0000-0000-000000000005', 1, 'approved', 1),
('30000000-0000-0000-0000-000000000006', '30000000-0000-0000-0000-000000000009', 4, 'pending',  1);

-- -------------------------------------------------------
-- FEMALE_MEDICAL_INFO (users 2 and 4 are female)
-- -------------------------------------------------------
INSERT INTO female_medical_info (user_id, menarche_age, pregnancies, births, abortions, menopause, menopause_age, contraceptive_use, intraceptive_method, contraceptive_reason) VALUES
('30000000-0000-0000-0000-000000000002', 13, 0, 0, 0, 0, NULL, 1, 'Pílula combinada', NULL),
('30000000-0000-0000-0000-000000000004', 12, 3, 3, 0, 1, 52,  0, NULL,                NULL);

-- -------------------------------------------------------
-- USER_SUBSCRIPTIONS
-- -------------------------------------------------------
INSERT INTO user_subscriptions (user_id, plan_id, card_type, start_date, end_date, is_active) VALUES
('30000000-0000-0000-0000-000000000001', 2, 'SC1', '2026-01-01', '2027-01-01', 1),
('30000000-0000-0000-0000-000000000002', 3, 'SC1', '2026-01-15', '2027-01-15', 1),
('30000000-0000-0000-0000-000000000003', 1, 'SC2', '2026-02-01', '2027-02-01', 1),
('30000000-0000-0000-0000-000000000004', 2, 'SC2', '2025-06-01', '2026-06-01', 1),
('30000000-0000-0000-0000-000000000005', 1, 'SC1', '2026-03-01', '2027-03-01', 1);

-- -------------------------------------------------------
-- INSTITUTION_LICENSES
-- -------------------------------------------------------
INSERT INTO institution_licenses (institution_id, billing_type, start_date, end_date, is_active) VALUES
('10000000-0000-0000-0000-000000000001', 'annual',  '2026-01-01', '2027-01-01', 1),
('10000000-0000-0000-0000-000000000002', 'monthly', '2026-01-01', '2026-12-31', 1),
('10000000-0000-0000-0000-000000000004', 'annual',  '2026-01-01', '2027-01-01', 1);

-- -------------------------------------------------------
-- ACCESS_REQUESTS
-- -------------------------------------------------------
INSERT INTO access_requests (user_id, doctor_id, requested_at, approved_at, expires_at, status, is_emergency, access_code) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', '2026-06-01 09:00:00', '2026-06-01 09:05:00', '2026-06-01 17:00:00', 'approved', 0, '847291'),
('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000002', '2026-06-10 14:30:00', '2026-06-10 14:32:00', '2026-06-10 18:00:00', 'approved', 0, '319284'),
('30000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000001', '2026-06-15 11:00:00', NULL,                   NULL,                  'pending',  0, '562938'),
('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000003', '2026-06-18 08:00:00', '2026-06-18 08:01:00', '2026-06-18 09:00:00', 'approved', 1, NULL);

-- -------------------------------------------------------
-- MEDICAL_FILES
-- -------------------------------------------------------
INSERT INTO medical_files (user_id, file_name, file_type, file_path, uploaded_by, uploaded_at) VALUES
('30000000-0000-0000-0000-000000000001', 'ecg_joao_silva_2026-06.pdf',      'application/pdf', 'users/1/exams/ecg_2026-06.pdf',        '20000000-0000-0000-0000-000000000001', '2026-06-01 10:00:00'),
('30000000-0000-0000-0000-000000000002', 'analises_ana_santos_2026-05.pdf', 'application/pdf', 'users/2/exams/analises_2026-05.pdf',   '20000000-0000-0000-0000-000000000002', '2026-05-15 09:30:00'),
('30000000-0000-0000-0000-000000000003', 'ressonancia_miguel_2025-12.pdf',  'application/pdf', 'users/3/exams/rmn_2025-12.pdf',        '20000000-0000-0000-0000-000000000003', '2025-12-10 14:00:00'),
('30000000-0000-0000-0000-000000000004', 'analises_maria_2026-04.pdf',      'application/pdf', 'users/4/exams/analises_2026-04.pdf',   '20000000-0000-0000-0000-000000000004', '2026-04-20 11:15:00'),
('30000000-0000-0000-0000-000000000001', 'relatorio_cirurgia_2020.pdf',     'application/pdf', 'users/1/history/cirurgia_2020.pdf',    '20000000-0000-0000-0000-000000000001', '2026-05-01 16:00:00');

-- -------------------------------------------------------
-- SURGICAL_HISTORY
-- -------------------------------------------------------
INSERT INTO surgical_history (user_id, surgery_name, surgery_date, location, notes, report_file_id, added_by, is_active) VALUES
('30000000-0000-0000-0000-000000000001', 'Apendicectomia',                '2020-03-15', 'Hospital de Santa Maria, Lisboa', 'Intervenção sem complicações. Alta ao 2º dia.',                    5,    '20000000-0000-0000-0000-000000000001', 1),
('30000000-0000-0000-0000-000000000004', 'Colecistectomia laparoscópica', '2018-09-22', 'CUF Descobertas, Lisboa',         'Remoção da vesícula biliar por cálculos. Bem tolerada.',            NULL, '20000000-0000-0000-0000-000000000002', 1),
('30000000-0000-0000-0000-000000000003', 'Artroscopia do joelho direito', '2022-05-10', 'Centro Hospitalar do Porto',      'Limpeza articular. Recuperação com fisioterapia durante 6 semanas.',NULL, '20000000-0000-0000-0000-000000000003', 1);

-- -------------------------------------------------------
-- CHRONIC_MEDICATIONS
-- -------------------------------------------------------
INSERT INTO chronic_medications (user_id, active_substance, dose, posology, start_date, end_date, prescribed_by, is_active) VALUES
('30000000-0000-0000-0000-000000000001', 'Ramipril',      '5 mg',   '1 comprimido/dia em jejum',                         '2022-01-10', NULL,         '20000000-0000-0000-0000-000000000001', 1),
('30000000-0000-0000-0000-000000000001', 'Atorvastatina', '20 mg',  '1 comprimido/dia ao jantar',                         '2022-01-10', NULL,         '20000000-0000-0000-0000-000000000001', 1),
('30000000-0000-0000-0000-000000000004', 'Metformina',    '850 mg', '1 comprimido 2x/dia às refeições',                  '2019-06-01', NULL,         '20000000-0000-0000-0000-000000000004', 1),
('30000000-0000-0000-0000-000000000004', 'Levotiroxina',  '75 µg',  '1 comprimido/dia 30 min antes do pequeno-almoço',  '2020-03-01', NULL,         '20000000-0000-0000-0000-000000000004', 1),
('30000000-0000-0000-0000-000000000003', 'Sertralina',    '50 mg',  '1 comprimido/dia de manhã',                         '2023-11-15', '2024-11-15', '20000000-0000-0000-0000-000000000003', 0);

-- -------------------------------------------------------
-- DRUG_ALLERGIES
-- -------------------------------------------------------
INSERT INTO drug_allergies (user_id, active_substance, allergic_reaction, severity) VALUES
('30000000-0000-0000-0000-000000000001', 'Penicilina',   'Erupção cutânea generalizada e edema facial', 'severe'),
('30000000-0000-0000-0000-000000000002', 'Ibuprofeno',   'Urticária e prurido',                         'moderate'),
('30000000-0000-0000-0000-000000000004', 'Sulfonamidas', 'Eritema multiforme',                          'severe'),
('30000000-0000-0000-0000-000000000003', 'Codeína',      'Náuseas e vómitos intensos',                  'mild');

-- -------------------------------------------------------
-- FAMILY_HISTORY
-- -------------------------------------------------------
INSERT INTO family_history (user_id, condition, has_condition, kinship_degree, notes) VALUES
('30000000-0000-0000-0000-000000000001', 'cardiovascular', 1, 'Pai',         'Pai faleceu de enfarte agudo do miocárdio aos 62 anos'),
('30000000-0000-0000-0000-000000000001', 'cancer',         0, NULL,           NULL),
('30000000-0000-0000-0000-000000000002', 'cancer',         1, 'Avó materna', 'Cancro da mama diagnosticado aos 55 anos'),
('30000000-0000-0000-0000-000000000004', 'cardiovascular', 1, 'Mãe',         'Hipertensão arterial e AVC isquémico'),
('30000000-0000-0000-0000-000000000004', 'genetic',        0, NULL,           NULL),
('30000000-0000-0000-0000-000000000003', 'psychological',  1, 'Irmão',       'Esquizofrenia diagnosticada na adolescência');

-- -------------------------------------------------------
-- USER_PATHOLOGIES
-- -------------------------------------------------------
INSERT INTO user_pathologies (user_id, icpc2_id, type, diagnosed_at, notes, added_by) VALUES
('30000000-0000-0000-0000-000000000001', 1, 'active',  '2022-01-10', 'HTA controlada com medicação. Monitorizar PA mensalmente.', '20000000-0000-0000-0000-000000000001'),
('30000000-0000-0000-0000-000000000004', 4, 'active',  '2019-06-01', 'DM2 com bom controlo glicémico. HbA1c 6.8%.',              '20000000-0000-0000-0000-000000000004'),
('30000000-0000-0000-0000-000000000003', 8, 'active',  '2021-03-15', 'Dor lombar crónica. Fisioterapia com melhoria parcial.',    '20000000-0000-0000-0000-000000000003'),
('30000000-0000-0000-0000-000000000002', 7, 'passive', '2020-09-01', 'Episódio resolvido sem sequelas.',                          '20000000-0000-0000-0000-000000000002');

-- -------------------------------------------------------
-- USER_SPECIALTY_FOLLOWUPS
-- -------------------------------------------------------
INSERT INTO user_specialty_followups (user_id, specialty_id, institution, start_date, notes) VALUES
('30000000-0000-0000-0000-000000000001', 1, 'Hospital de Santa Maria',    '2022-01-15', 'Seguimento em cardiologia por HTA e dislipidémia'),
('30000000-0000-0000-0000-000000000004', 7, 'Hospital de Santa Maria',    '2019-06-15', 'Seguimento em endocrinologia por DM2 e hipotiroidismo'),
('30000000-0000-0000-0000-000000000003', 9, 'Centro Hospitalar do Porto', '2023-11-20', 'Consulta de psiquiatria por episódio depressivo maior');

-- -------------------------------------------------------
-- ANALYTICAL_EXAMS
-- -------------------------------------------------------
INSERT INTO analytical_exams (user_id, exam_date, laboratory, file_id, notes, added_by, is_active) VALUES
('30000000-0000-0000-0000-000000000002', '2026-05-10', 'Germano de Sousa', 2,    'Análises de rotina anuais',              '20000000-0000-0000-0000-000000000002', 1),
('30000000-0000-0000-0000-000000000004', '2026-04-15', 'Germano de Sousa', 4,    'Controlo de DM2 e perfil lipídico',      '20000000-0000-0000-0000-000000000004', 1),
('30000000-0000-0000-0000-000000000001', '2026-06-01', 'Germano de Sousa', NULL, 'Perfil cardiovascular',                  '20000000-0000-0000-0000-000000000001', 1);

-- -------------------------------------------------------
-- ANALYTICAL_EXAM_PARAMETERS
-- -------------------------------------------------------
INSERT INTO analytical_exam_parameters (exam_id, parameter_name, value, unit, reference_min, reference_max, is_abnormal) VALUES
-- exam 1 — Ana Santos
(1, 'Glicose',          89.0,  'mg/dL', 70.0, 110.0, 0),
(1, 'Colesterol total', 195.0, 'mg/dL', NULL, 200.0, 0),
(1, 'HDL',              62.0,  'mg/dL', 50.0, NULL,  0),
(1, 'LDL',              118.0, 'mg/dL', NULL, 130.0, 0),
(1, 'Triglicerídeos',   85.0,  'mg/dL', NULL, 150.0, 0),
(1, 'Hemoglobina',      13.8,  'g/dL',  12.0, 16.0,  0),
-- exam 2 — Maria Pereira
(2, 'HbA1c',            6.8,   '%',     NULL, 7.0,   0),
(2, 'Glicose em jejum', 128.0, 'mg/dL', 70.0, 110.0, 1),
(2, 'TSH',              2.1,   'µUI/mL',0.4,  4.0,   0),
(2, 'Colesterol total', 212.0, 'mg/dL', NULL, 200.0, 1),
-- exam 3 — João Silva
(3, 'Colesterol total', 178.0, 'mg/dL', NULL, 200.0, 0),
(3, 'LDL',              95.0,  'mg/dL', NULL, 130.0, 0),
(3, 'PCR',              0.3,   'mg/L',  NULL, 1.0,   0);

-- -------------------------------------------------------
-- IMAGING_EXAMS
-- -------------------------------------------------------
INSERT INTO imaging_exams (user_id, exam_type, body_area, exam_date, institution, file_id, report_text, added_by, is_active) VALUES
('30000000-0000-0000-0000-000000000003', 'Ressonância Magnética', 'Coluna lombar', '2025-12-05', 'Centro Hospitalar do Porto', 3,    'Hérnias discais L4-L5 e L5-S1 com componente extrusivo. Compromisso radicular moderado.', '20000000-0000-0000-0000-000000000003', 1),
('30000000-0000-0000-0000-000000000001', 'Ecocardiograma',        'Coração',       '2026-05-20', 'Hospital de Santa Maria',    NULL, 'FE preservada 62%. Sem alterações valvulares significativas. HVE ligeira.',               '20000000-0000-0000-0000-000000000001', 1);

-- -------------------------------------------------------
-- OPTOMETRY_EXAMS
-- -------------------------------------------------------
INSERT INTO optometry_exams (user_id, exam_date, right_sphere, right_cylinder, right_axis, left_sphere, left_cylinder, left_axis, disease_report, added_by, is_active) VALUES
('30000000-0000-0000-0000-000000000002', '2026-03-10', -1.25, -0.50, 180, -1.00, -0.25, 175, 'Sem patologia ocular. Miopia ligeira bilateral.',   '20000000-0000-0000-0000-000000000002', 1),
('30000000-0000-0000-0000-000000000004', '2025-11-20', -0.50,  0.00,   0, -0.75,  0.00,   0, 'Presbiopia. Sem outras alterações de relevo.',      '20000000-0000-0000-0000-000000000002', 1);

-- -------------------------------------------------------
-- USER_VACCINATIONS
-- -------------------------------------------------------
INSERT INTO user_vaccinations (user_id, vaccine_id, dose_number, administered_at, next_due_date, batch_number, institution, notes, added_by) VALUES
('30000000-0000-0000-0000-000000000001', 3,  '5ª dose (reforço)', '2010-09-01', NULL,         'DTP-2010-A', 'Centro de Saúde da Ajuda',           'Reforço em adulto',  '20000000-0000-0000-0000-000000000002'),
('30000000-0000-0000-0000-000000000001', 10, 'Dose anual',        '2025-10-15', '2026-10-15', 'FLU-2025-B', 'Farmácia Saúde Lisboa',              'Gripe sazonal',      '20000000-0000-0000-0000-000000000002'),
('30000000-0000-0000-0000-000000000002', 10, 'Dose anual',        '2025-10-20', '2026-10-20', 'FLU-2025-C', 'Centro de Saúde de Arroios',         'Gripe sazonal',      '20000000-0000-0000-0000-000000000002'),
('30000000-0000-0000-0000-000000000004', 7,  '2ª dose (reforço)', '2005-05-10', NULL,         'MMR-2005-X', 'Centro de Saúde de Campolide',       'Reforço VASPR',      '20000000-0000-0000-0000-000000000002'),
('30000000-0000-0000-0000-000000000005', 1,  '1ª dose',           '2005-09-15', NULL,         'BCG-2005-Z', 'Maternidade Dr. Alfredo Costa',      NULL,                 '20000000-0000-0000-0000-000000000002');

-- -------------------------------------------------------
-- HEALTH_HABITS
-- details: JSON with type-specific fields
-- type_id references HABIT_TYPES.id
-- -------------------------------------------------------
INSERT INTO health_habits (user_id, type_id, name, consumes, frequency, quantity, start_date, details) VALUES
('30000000-0000-0000-0000-000000000001', 1, NULL,       1,    'Fins de semana', '2-3 bebidas', '2010-01-01', '{"alcohol_type":"Vinho tinto","in_detox":false,"audit_c_score":3,"audit_score":5}'),
('30000000-0000-0000-0000-000000000001', 5, 'Corrida',  NULL, '3x por semana',  '5-8 km',     '2018-06-01', '{"activity":"Corrida"}'),
('30000000-0000-0000-0000-000000000002', 5, 'Natação',  NULL, '2x por semana',  '1 hora',     '2020-01-01', '{"activity":"Natação"}'),
('30000000-0000-0000-0000-000000000003', 2, NULL,       0,    NULL,              NULL,         '2015-03-01', '{"consumes":false,"cigarettes_per_day":0,"years_consumption":8,"pack_years":4.0,"fagerstrom_score":0,"richmond_score":9}'),
('30000000-0000-0000-0000-000000000004', 1, NULL,       0,    NULL,              NULL,         NULL,          '{"alcohol_type":null,"in_detox":false,"audit_c_score":0,"audit_score":0}'),
('30000000-0000-0000-0000-000000000005', 5, 'Futebol',  NULL, '2x por semana',  '90 min',     '2023-09-01', '{"activity":"Futebol"}');

-- -------------------------------------------------------
-- DOCTOR_NOTES
-- note_text is NULL — encryption is done at the application layer
-- -------------------------------------------------------
INSERT INTO doctor_notes (user_id, doctor_id, section, note_text) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'medical_info', NULL),
('30000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000004', 'medical_info', NULL),
('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000003', 'habits',       NULL);

-- -------------------------------------------------------
-- PENDING_REVIEW_FLAGS
-- -------------------------------------------------------
INSERT INTO pending_review_flags (user_id, section, created_at, reviewed_at, reviewed_by) VALUES
('30000000-0000-0000-0000-000000000002', 'habits',        '2026-06-10 14:00:00', NULL,                  NULL),
('30000000-0000-0000-0000-000000000004', 'medical_info',  '2026-06-12 09:00:00', '2026-06-13 10:30:00', '20000000-0000-0000-0000-000000000004'),
('30000000-0000-0000-0000-000000000005', 'identification','2026-06-20 08:00:00', NULL,                  NULL);

-- -------------------------------------------------------
-- SCHEMA_VERSIONS
-- -------------------------------------------------------
INSERT INTO schema_versions (version, description, script, applied_by, checksum, success) VALUES
('001', 'Schema inicial — todas as tabelas base',              'schema_v001_initial.sql',       'system', 'a3f8c1d2e4b5f6a7', 1),
('002', 'Adicionar is_active a USERS, DOCTORS e exames',       'schema_v002_is_active.sql',     'system', 'b4e9d2f3a5c6b7e8', 1),
('003', 'Consolidar HEALTH_HABIT_* em HEALTH_HABITS',          'schema_v003_health_habits.sql', 'system', 'c5f0e3a4b6d7c8f9', 1),
('004', 'Adicionar SCHEMA_VERSIONS e APP_VERSIONS',            'schema_v004_versioning.sql',    'system', 'd6a1f4b5c7e8d9a0', 1),
('005', 'users.id, doctors.id e institutions.id passam a GUID','schema_v005_guid_ids.sql',      'system', 'e7b2a5c6d8f9e0b1', 1),
('006', 'GENDERS e HABIT_TYPES como config tables; billing_type com mais opções', 'schema_v006_config_tables.sql', 'system', 'f8c3b6d7e9f0a1c2', 1),
('007', 'Adicionar COUNTRIES e nationality_id a USERS e DOCTORS (KAN-22)', 'schema_v007_nationality.sql', 'system', 'a9d4c7e8f0a1b2d3', 1);

-- -------------------------------------------------------
-- APP_VERSIONS
-- -------------------------------------------------------
INSERT INTO app_versions (version, release_date, description, deployed_by, environment, is_current) VALUES
('0.1.0', '2026-05-01', 'Versão inicial — autenticação e perfil de utilizador', 'braulio.batista', 'dev', 0),
('0.2.0', '2026-06-01', 'MCDTS — exames analíticos e de imagem',                'braulio.batista', 'dev', 0),
('0.3.0', '2026-06-21', 'Hábitos de saúde consolidados e versionamento',        'braulio.batista', 'dev', 1);

-- -------------------------------------------------------
-- SCHEDULE_EVENT_TYPES
-- -------------------------------------------------------
INSERT INTO schedule_event_types (code, description) VALUES
('CONGRESS', 'Congresso'),
('TRAINING', 'Formação'),
('VACATION', 'Férias');

-- -------------------------------------------------------
-- APPOINTMENT_TYPES
-- -------------------------------------------------------
INSERT INTO appointment_types (code, description) VALUES
('CONSULTATION', 'Consulta'),
('FOLLOWUP',     'Acompanhamento'),
('EXAM',         'Exame'),
('RETURN',       'Retorno');

-- -------------------------------------------------------
-- INSTITUTION_CONTACTS
-- -------------------------------------------------------
INSERT INTO institution_contacts (institution_id, service_name, extension, is_active) VALUES
('10000000-0000-0000-0000-000000000001', 'Receção Principal',          '+351 210 000 100', 1),
('10000000-0000-0000-0000-000000000001', 'Secretaria de Cardiologia',  '+351 210 000 101', 1),
('10000000-0000-0000-0000-000000000001', 'Enfermaria 2º Andar',        '+351 210 000 102', 1),
('10000000-0000-0000-0000-000000000001', 'Exames – Marcação',          '+351 210 000 103', 1),
('10000000-0000-0000-0000-000000000002', 'Apoio ao Utente',            '+351 210 025 210', 1),
('10000000-0000-0000-0000-000000000002', 'Farmácia Hospitalar',        '+351 210 025 211', 1);

-- -------------------------------------------------------
-- DOCTOR_SCHEDULE_EVENTS
-- -------------------------------------------------------
INSERT INTO doctor_schedule_events (doctor_id, event_type_id, title, location, start_date, end_date, notes) VALUES
('20000000-0000-0000-0000-000000000001', 1, 'Congresso Nacional de Cardiologia', 'Lisboa, Portugal', '2026-05-15', '2026-05-17', NULL),
('20000000-0000-0000-0000-000000000001', 1, 'European Society of Cardiology',    'Madrid, Espanha',  '2026-06-05', '2026-06-07', NULL),
('20000000-0000-0000-0000-000000000001', 3, 'Período de Férias',                 NULL,               '2026-08-02', '2026-08-08', NULL),
('20000000-0000-0000-0000-000000000003', 2, 'Formação em Neurologia Pediátrica', 'Porto, Portugal',  '2026-05-22', '2026-05-23', 'Ação de formação interna');

-- -------------------------------------------------------
-- PATIENT_APPOINTMENTS
-- -------------------------------------------------------
INSERT INTO patient_appointments (user_id, doctor_id, appointment_type_id, modality, scheduled_at, status, created_by_role, created_by_doctor_id) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 1, 'presencial',   '2026-05-10 09:00:00', 'em_curso',   'doctor', '20000000-0000-0000-0000-000000000001'),
('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 1, 'presencial',   '2026-05-10 10:30:00', 'confirmada', 'staff',  NULL),
('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000001', 1, 'teleconsulta', '2026-05-10 11:30:00', 'confirmada', 'staff',  NULL),
('30000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000001', 4, 'presencial',   '2026-05-10 14:00:00', 'confirmada', 'doctor', '20000000-0000-0000-0000-000000000001'),
('30000000-0000-0000-0000-000000000005', '20000000-0000-0000-0000-000000000001', 1, 'presencial',   '2026-05-10 15:30:00', 'confirmada', 'staff',  NULL),
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 1, 'presencial',   '2026-07-26 09:00:00', 'em_curso',   'staff',  NULL),
('30000000-0000-0000-0000-000000000002', '20000000-0000-0000-0000-000000000001', 1, 'presencial',   '2026-07-26 10:30:00', 'confirmada', 'staff',  NULL),
('30000000-0000-0000-0000-000000000003', '20000000-0000-0000-0000-000000000001', 1, 'teleconsulta', '2026-07-26 11:30:00', 'confirmada', 'staff',  NULL),
('30000000-0000-0000-0000-000000000004', '20000000-0000-0000-0000-000000000001', 4, 'presencial',   '2026-07-26 14:00:00', 'confirmada', 'doctor', '20000000-0000-0000-0000-000000000001');

-- -------------------------------------------------------
-- VITAL_SIGNS
-- -------------------------------------------------------
INSERT INTO vital_signs (user_id, doctor_id, recorded_at, blood_pressure_systolic, blood_pressure_diastolic, heart_rate, respiratory_rate, temperature, spo2, weight, height, notes) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', '2026-07-26 10:30:00', 128, 80, 72, 16, 36.6, 98, 72.4, 168,
 'Doente com bom aspeto geral, eupneico em repouso. Auscultação cardíaca com sopro sistólico II/VI no foco mitral. Sem edemas periféricos. Abdómen mole e depressível, sem massas palpáveis.');

-- -------------------------------------------------------
-- CLINICAL_ASSESSMENTS
-- -------------------------------------------------------
INSERT INTO clinical_assessments (user_id, doctor_id, hypothesis, plan) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'Insuficiência Cardíaca', 'Ecocardiograma transtorácico, NT-proBNP, RX tórax'),
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'Doença arterial coronária', 'Teste provocação isquémica, ECG de esforço');

-- -------------------------------------------------------
-- ANAMNESES
-- -------------------------------------------------------
INSERT INTO anamneses (user_id, doctor_id, chief_complaint, illness_history, personal_history) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001',
 'Dispneia aos esforços médios (subir escadas), fadiga fácil, sem dor torácica.',
 'Sintomas iniciados há cerca de 3 semanas, progressivos. Nega ortopneia, PND ou edema.',
 'Hipertensão arterial diagnosticada há 5 anos. Dislipidemia.');

-- -------------------------------------------------------
-- PATIENT_CHAT_MESSAGES
-- -------------------------------------------------------
INSERT INTO patient_chat_messages (user_id, author_doctor_id, message, created_at) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000002',
 'Bom dia Carlos, o João esteve cá esta semana queixando-se de fadiga fácil e dispneia. Podes dar uma vista de olhos do lado da cardiologia?', '2026-07-24 09:00:00'),
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001',
 'Bom dia, obrigado pelo aviso. Vou pedir um ecocardiograma e reavaliar a medicação anti-hipertensiva dele.', '2026-07-24 12:00:00'),
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001',
 'Resultados do eco dentro da normalidade, função sistólica preservada. Reveja os resultados anexados nos documentos.', '2026-07-27 15:00:00');

-- -------------------------------------------------------
-- CONSULTATIONS
-- -------------------------------------------------------
INSERT INTO consultations (user_id, doctor_id, status, started_at, finished_at) VALUES
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000001', 'finished', '2026-07-24 09:30:00', '2026-07-24 09:55:00'),
('30000000-0000-0000-0000-000000000001', '20000000-0000-0000-0000-000000000002', 'draft', '2026-08-14 10:00:00', NULL);
